// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: value.proto

package valuepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictLTVRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Features      map[string]float32     `protobuf:"bytes,2,rep,name=features,proto3" json:"features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictLTVRequest) Reset() {
	*x = PredictLTVRequest{}
	mi := &file_value_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictLTVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictLTVRequest) ProtoMessage() {}

func (x *PredictLTVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_value_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictLTVRequest.ProtoReflect.Descriptor instead.
func (*PredictLTVRequest) Descriptor() ([]byte, []int) {
	return file_value_proto_rawDescGZIP(), []int{0}
}

func (x *PredictLTVRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PredictLTVRequest) GetFeatures() map[string]float32 {
	if x != nil {
		return x.Features
	}
	return nil
}

type PredictLTVResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Ltv           float32                `protobuf:"fixed32,2,opt,name=ltv,proto3" json:"ltv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictLTVResponse) Reset() {
	*x = PredictLTVResponse{}
	mi := &file_value_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictLTVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictLTVResponse) ProtoMessage() {}

func (x *PredictLTVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_value_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictLTVResponse.ProtoReflect.Descriptor instead.
func (*PredictLTVResponse) Descriptor() ([]byte, []int) {
	return file_value_proto_rawDescGZIP(), []int{1}
}

func (x *PredictLTVResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PredictLTVResponse) GetLtv() float32 {
	if x != nil {
		return x.Ltv
	}
	return 0
}

type TrainLTVRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasetPath   string                 `protobuf:"bytes,1,opt,name=dataset_path,json=datasetPath,proto3" json:"dataset_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainLTVRequest) Reset() {
	*x = TrainLTVRequest{}
	mi := &file_value_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainLTVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainLTVRequest) ProtoMessage() {}

func (x *TrainLTVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_value_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainLTVRequest.ProtoReflect.Descriptor instead.
func (*TrainLTVRequest) Descriptor() ([]byte, []int) {
	return file_value_proto_rawDescGZIP(), []int{2}
}

func (x *TrainLTVRequest) GetDatasetPath() string {
	if x != nil {
		return x.DatasetPath
	}
	return ""
}

type TrainLTVResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainLTVResponse) Reset() {
	*x = TrainLTVResponse{}
	mi := &file_value_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainLTVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainLTVResponse) ProtoMessage() {}

func (x *TrainLTVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_value_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainLTVResponse.ProtoReflect.Descriptor instead.
func (*TrainLTVResponse) Descriptor() ([]byte, []int) {
	return file_value_proto_rawDescGZIP(), []int{3}
}

func (x *TrainLTVResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_value_proto protoreflect.FileDescriptor

const file_value_proto_rawDesc = "" +
	"\n" +
	"\vvalue.proto\x12\x05value\"\xad\x01\n" +
	"\x11PredictLTVRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12B\n" +
	"\bfeatures\x18\x02 \x03(\v2&.value.PredictLTVRequest.FeaturesEntryR\bfeatures\x1a;\n" +
	"\rFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"?\n" +
	"\x12PredictLTVResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03ltv\x18\x02 \x01(\x02R\x03ltv\"4\n" +
	"\x0fTrainLTVRequest\x12!\n" +
	"\fdataset_path\x18\x01 \x01(\tR\vdatasetPath\"*\n" +
	"\x10TrainLTVResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x8c\x01\n" +
	"\n" +
	"LTVService\x12A\n" +
	"\n" +
	"PredictLTV\x12\x18.value.PredictLTVRequest\x1a\x19.value.PredictLTVResponse\x12;\n" +
	"\bTrainLTV\x12\x16.value.TrainLTVRequest\x1a\x17.value.TrainLTVResponseB5Z3github.com/kiki-agent/shared/types/go/value;valuepbb\x06proto3"

var (
	file_value_proto_rawDescOnce sync.Once
	file_value_proto_rawDescData []byte
)

func file_value_proto_rawDescGZIP() []byte {
	file_value_proto_rawDescOnce.Do(func() {
		file_value_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_value_proto_rawDesc), len(file_value_proto_rawDesc)))
	})
	return file_value_proto_rawDescData
}

var file_value_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_value_proto_goTypes = []any{
	(*PredictLTVRequest)(nil),  // 0: value.PredictLTVRequest
	(*PredictLTVResponse)(nil), // 1: value.PredictLTVResponse
	(*TrainLTVRequest)(nil),    // 2: value.TrainLTVRequest
	(*TrainLTVResponse)(nil),   // 3: value.TrainLTVResponse
	nil,                        // 4: value.PredictLTVRequest.FeaturesEntry
}
var file_value_proto_depIdxs = []int32{
	4, // 0: value.PredictLTVRequest.features:type_name -> value.PredictLTVRequest.FeaturesEntry
	0, // 1: value.LTVService.PredictLTV:input_type -> value.PredictLTVRequest
	2, // 2: value.LTVService.TrainLTV:input_type -> value.TrainLTVRequest
	1, // 3: value.LTVService.PredictLTV:output_type -> value.PredictLTVResponse
	3, // 4: value.LTVService.TrainLTV:output_type -> value.TrainLTVResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_value_proto_init() }
func file_value_proto_init() {
	if File_value_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_value_proto_rawDesc), len(file_value_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_value_proto_goTypes,
		DependencyIndexes: file_value_proto_depIdxs,
		MessageInfos:      file_value_proto_msgTypes,
	}.Build()
	File_value_proto = out.File
	file_value_proto_goTypes = nil
	file_value_proto_depIdxs = nil
}
