package internal
























































































































































































}	return "success_fee_invoices"func (SuccessFeeInvoice) TableName() string {}	return "attribution_logs"func (AttributionLog) TableName() string {}	return "baseline_snapshots"func (BaselineSnapshot) TableName() string {}	return "ledger_entries"func (LedgerEntry) TableName() string {// TableName customization (optional)}	ApprovedAt  *time.Time `json:"approved_at"`	ApprovedBy  *string `json:"approved_by"`	GeneratedBy string `gorm:"type:varchar(100)" json:"generated_by"` // System or manual	// Audit	ExplanationSent bool `gorm:"default:false" json:"explanation_sent"` // Whether XAI report was sent	NotificationSentAt *time.Time `json:"notification_sent_at"`	ClientNotified bool `gorm:"default:false" json:"client_notified"`	// Client Communication	InvoiceURL   *string `json:"invoice_url"` // Link to PDF invoice	DueDate      time.Time `json:"due_date"`	PaidAt       *time.Time `json:"paid_at"`	SentAt       *time.Time `json:"sent_at"`	Status       string `gorm:"type:varchar(20);default:'draft'" json:"status"` // draft, sent, paid, disputed	// Invoice Status	TopContributingAgents string `gorm:"type:jsonb" json:"top_contributing_agents"` // {"SyncFlow": 0.45, "SyncEngage": 0.30}	AttributionStats     string `gorm:"type:jsonb" json:"attribution_stats"` // {"high_confidence": 50, "medium": 20, "low": 5}	// Attribution Breakdown (XAI)	TotalOrdersAttrributed int `gorm:"not null" json:"total_orders_attributed"`	SuccessFeeAmount     float64 `gorm:"type:decimal(12,2);not null" json:"success_fee_amount"`	SuccessFeePercentage float64 `gorm:"type:decimal(4,2);default:20.00" json:"success_fee_percentage"` // Default 20%	// Success Fee Calculation	UpliftPercentage     float64 `gorm:"type:decimal(5,2)" json:"uplift_percentage"`             // (Incremental / Baseline) * 100	IncrementalRevenue   float64 `gorm:"type:decimal(12,2);not null" json:"incremental_revenue"` // Actual - Baseline	ActualRevenue        float64 `gorm:"type:decimal(12,2);not null" json:"actual_revenue"`	BaselineRevenue      float64 `gorm:"type:decimal(12,2);not null" json:"baseline_revenue"`	// Revenue Summary	BillingYear  int `gorm:"not null" json:"billing_year"`  // 2024, 2025, etc.	BillingMonth int `gorm:"not null" json:"billing_month"` // 1-12	// Billing Period	Platform string `gorm:"type:varchar(50);not null" json:"platform"`	StoreID  int    `gorm:"index;not null" json:"store_id"`	UpdatedAt time.Time `json:"updated_at"`	CreatedAt time.Time `json:"created_at"`	ID        uint      `gorm:"primaryKey" json:"id"`type SuccessFeeInvoice struct {// SuccessFeeInvoice represents a monthly billing period for OaaS}	ReviewedAt   *time.Time `json:"reviewed_at"`	ReviewedBy   *string `json:"reviewed_by"`   // Admin who reviewed (if manual override)	AttributedBy string `gorm:"type:varchar(100)" json:"attributed_by"` // System or manual override	// Audit Trail	CounterfactualRevenue float64 `gorm:"type:decimal(12,2)" json:"counterfactual_revenue"` // Estimated revenue without KIKI	Explanation     string `gorm:"type:text" json:"explanation"` // Human-readable attribution reason	// XAI (Explainability) Output	SyncEngageContribution float64 `gorm:"type:decimal(3,2)" json:"syncengage_contribution"` // Nurture flow impact	SyncCreateContribution float64 `gorm:"type:decimal(3,2)" json:"synccreate_contribution"` // Creative performance	SyncFlowContribution   float64 `gorm:"type:decimal(3,2)" json:"syncflow_contribution"`   // Bid optimization impact	SyncValueContribution  float64 `gorm:"type:decimal(3,2)" json:"syncvalue_contribution"`  // LTV prediction accuracy	// Agent Contributions (which agents influenced this sale)	ThresholdApplied float64 `gorm:"type:decimal(3,2);default:0.70" json:"threshold_applied"` // Confidence threshold	FinalConfidence  float64 `gorm:"type:decimal(3,2);not null" json:"final_confidence"`	SignalScores     string  `gorm:"type:jsonb" json:"signal_scores"`         // {"ad_touchpoint": 0.5, "acquisition": 0.5, "promotion": 0.3}	DecisionEngine   string  `gorm:"type:varchar(50)" json:"decision_engine"` // "multi_signal_v1", "ml_model_v2"	// Attribution Decision Process	OrderID       int  `gorm:"index;not null" json:"order_id"`	StoreID       int  `gorm:"index;not null" json:"store_id"`	LedgerEntryID uint `gorm:"index;not null" json:"ledger_entry_id"`	CreatedAt time.Time `json:"created_at"`	ID        uint      `gorm:"primaryKey" json:"id"`type AttributionLog struct {// AttributionLog stores detailed attribution decision logs for debugging/transparency}	LastSyncedAt time.Time `json:"last_synced_at"`	// Last updated from SyncValue	TotalSuccessFees     float64 `gorm:"type:decimal(12,2);default:0.00" json:"total_success_fees"`	TotalIncrementalRevenue float64 `gorm:"type:decimal(12,2);default:0.00" json:"total_incremental_revenue"`	CurrentOrders        int     `gorm:"default:0" json:"current_orders"`	CurrentRevenue       float64 `gorm:"type:decimal(12,2);default:0.00" json:"current_revenue"`	// KIKI Performance Comparison	DataQuality          string    `gorm:"type:varchar(20);default:'high'" json:"data_quality"` // high, medium, low	TotalOrdersAnalyzed  int       `json:"total_orders_analyzed"`	CalculationEndDate   time.Time `gorm:"not null" json:"calculation_end_date"`   // e.g., KIKI install date	CalculationStartDate time.Time `gorm:"not null" json:"calculation_start_date"` // e.g., 12 months ago	// Calculation Period	BaselineConversionRate  float64 `gorm:"type:decimal(5,2)" json:"baseline_conversion_rate"`	BaselineRepeatRate      float64 `gorm:"type:decimal(5,2)" json:"baseline_repeat_rate"` // Percentage	BaselineAvgOrderValue   float64 `gorm:"type:decimal(10,2)" json:"baseline_avg_order_value"`	BaselineOrders          int     `gorm:"not null" json:"baseline_orders"`	BaselineRevenue         float64 `gorm:"type:decimal(12,2);not null" json:"baseline_revenue"`	// Baseline Metrics (calculated from 12-month historical data)	Platform string `gorm:"type:varchar(50);not null" json:"platform"`	StoreID  int    `gorm:"uniqueIndex;not null" json:"store_id"`	UpdatedAt time.Time `json:"updated_at"`	CreatedAt time.Time `json:"created_at"`	ID        uint      `gorm:"primaryKey" json:"id"`type BaselineSnapshot struct {// Used to calculate real-time uplift: Current Revenue - Baseline = Incremental// BaselineSnapshot stores the "Pre-KIKI" historical performance metrics}	return nil	l.EntryHash = uuid.New().String()	// Generate UUID-based hash for immutabilityfunc (l *LedgerEntry) BeforeCreate(tx *gorm.DB) error {// BeforeCreate hook to generate immutable hash}	SettlementDate *time.Time `json:"settlement_date"`	InvoiceStatus  string `gorm:"type:varchar(20);default:'pending'" json:"invoice_status"` // pending, invoiced, paid	InvoiceID      *uint  `json:"invoice_id"`      // Foreign key to SuccessFeeInvoice	// Invoice Tracking	AgentsInvolved    string `gorm:"type:jsonb" json:"agents_involved"`   // JSON array: ["SyncValue", "SyncFlow", "SyncEngage"]	AttributionReason string `gorm:"type:text" json:"attribution_reason"` // Human-readable explanation	// Metadata for XAI (Explainability)	TouchpointID *string `json:"touchpoint_id"` // Ad click/impression ID	CreativeID   *string `json:"creative_id"`   // SyncCreate creative ID	CampaignID   *string `json:"campaign_id"`   // SyncFlow campaign ID	// Campaign Attribution (which KIKI actions influenced this sale)	FeeApplicable    bool    `gorm:"not null;default:false" json:"fee_applicable"`	SuccessFeeAmount float64 `gorm:"type:decimal(12,2);default:0.00" json:"success_fee_amount"` // 20% of incremental	// Success Fee Calculation	UpliftPercentage       float64 `gorm:"type:decimal(5,2)" json:"uplift_percentage"`          // (Current - Baseline) / Baseline * 100	BaselineRevenue        float64 `gorm:"type:decimal(12,2);not null" json:"baseline_revenue"` // Pre-KIKI historical average	IncrementalRevenue     float64 `gorm:"type:decimal(12,2);default:0.00" json:"incremental_revenue"`	AttributionConfidence  float64 `gorm:"type:decimal(3,2);not null" json:"attribution_confidence"` // 0.0-1.0	AttributedToKIKI       bool    `gorm:"not null;default:false" json:"attributed_to_kiki"`	// Attribution Data	OrderAmount     float64 `gorm:"type:decimal(12,2);not null" json:"order_amount"` // Total order value	PlatformOrderID string  `gorm:"index;not null" json:"platform_order_id"`	OrderID         int     `gorm:"not null" json:"order_id"` // Internal order ID	// Order Details (from CMS webhook)	Platform string `gorm:"type:varchar(50);not null" json:"platform"` // shopify, woocommerce, etc.	StoreID  int    `gorm:"index;not null" json:"store_id"`	// Store & Platform	CreatedAt time.Time `json:"created_at"`	EntryHash string    `gorm:"uniqueIndex;not null" json:"entry_hash"` // SHA-256 hash for immutability	ID        uint      `gorm:"primaryKey" json:"id"`type LedgerEntry struct {// This is the core "Truth Ledger" that proves KIKI's value// LedgerEntry represents a single immutable financial transaction record)	"gorm.io/gorm"	"github.com/google/uuid"	"time"import (package models