# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brain.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'brain.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62rain.proto\x12\x05\x62rain\"\xa4\x01\n\x12OrchestrateRequest\x12\x13\n\x0b\x63\x61mpaign_id\x18\x01 \x01(\t\x12\x10\n\x08user_ids\x18\x02 \x03(\t\x12\x37\n\x07\x63ontext\x18\x03 \x03(\x0b\x32&.brain.OrchestrateRequest.ContextEntry\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"K\n\x13OrchestrateResponse\x12\x13\n\x0b\x63\x61mpaign_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x63tions\x18\x02 \x03(\t\x12\x0e\n\x06status\x18\x03 \x01(\t2\\\n\x14StrategyOrchestrator\x12\x44\n\x0bOrchestrate\x12\x19.brain.OrchestrateRequest\x1a\x1a.brain.OrchestrateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'brain_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORCHESTRATEREQUEST_CONTEXTENTRY']._loaded_options = None
  _globals['_ORCHESTRATEREQUEST_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_ORCHESTRATEREQUEST']._serialized_start=23
  _globals['_ORCHESTRATEREQUEST']._serialized_end=187
  _globals['_ORCHESTRATEREQUEST_CONTEXTENTRY']._serialized_start=141
  _globals['_ORCHESTRATEREQUEST_CONTEXTENTRY']._serialized_end=187
  _globals['_ORCHESTRATERESPONSE']._serialized_start=189
  _globals['_ORCHESTRATERESPONSE']._serialized_end=264
  _globals['_STRATEGYORCHESTRATOR']._serialized_start=266
  _globals['_STRATEGYORCHESTRATOR']._serialized_end=358
# @@protoc_insertion_point(module_scope)
