// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: syncledger.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Money represents a monetary amount with currency
type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"` // ISO 4217 currency code (e.g., "USD")
	Units         int64                  `protobuf:"varint,2,opt,name=units,proto3" json:"units,omitempty"`      // Whole currency units (e.g., 99 for $99.99)
	Nanos         int32                  `protobuf:"varint,3,opt,name=nanos,proto3" json:"nanos,omitempty"`      // Nano units (e.g., 990000000 for $0.99)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_syncledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_syncledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_syncledger_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Money) GetUnits() int64 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *Money) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

// IncrementalRevenueRequest is sent by SyncPortal when an order is attributed
type IncrementalRevenueRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	StoreId               int32                  `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`                                                                                           // Shopify store ID
	OrderId               int32                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                                                                                           // Internal order ID
	PlatformOrderId       string                 `protobuf:"bytes,3,opt,name=platform_order_id,json=platformOrderId,proto3" json:"platform_order_id,omitempty"`                                                                  // Shopify/WooCommerce order ID
	Platform              string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`                                                                                                         // "shopify", "woocommerce", "bigcommerce"
	OrderAmount           *Money                 `protobuf:"bytes,5,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"`                                                                                // Total order amount
	IncrementalAmount     *Money                 `protobuf:"bytes,6,opt,name=incremental_amount,json=incrementalAmount,proto3" json:"incremental_amount,omitempty"`                                                              // Amount above baseline (calculated by attribution engine)
	AttributionConfidence float32                `protobuf:"fixed32,7,opt,name=attribution_confidence,json=attributionConfidence,proto3" json:"attribution_confidence,omitempty"`                                                // 0.0-1.0 confidence score
	CampaignId            string                 `protobuf:"bytes,8,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`                                                                                   // SyncFlow campaign ID (if ad-driven)
	SignalScores          map[string]float32     `protobuf:"bytes,9,rep,name=signal_scores,json=signalScores,proto3" json:"signal_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"` // XAI: {"ad_touchpoint": 0.5, "product_promo": 0.3, "nurture": 0.2}
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *IncrementalRevenueRequest) Reset() {
	*x = IncrementalRevenueRequest{}
	mi := &file_syncledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementalRevenueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementalRevenueRequest) ProtoMessage() {}

func (x *IncrementalRevenueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementalRevenueRequest.ProtoReflect.Descriptor instead.
func (*IncrementalRevenueRequest) Descriptor() ([]byte, []int) {
	return file_syncledger_proto_rawDescGZIP(), []int{1}
}

func (x *IncrementalRevenueRequest) GetStoreId() int32 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *IncrementalRevenueRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *IncrementalRevenueRequest) GetPlatformOrderId() string {
	if x != nil {
		return x.PlatformOrderId
	}
	return ""
}

func (x *IncrementalRevenueRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *IncrementalRevenueRequest) GetOrderAmount() *Money {
	if x != nil {
		return x.OrderAmount
	}
	return nil
}

func (x *IncrementalRevenueRequest) GetIncrementalAmount() *Money {
	if x != nil {
		return x.IncrementalAmount
	}
	return nil
}

func (x *IncrementalRevenueRequest) GetAttributionConfidence() float32 {
	if x != nil {
		return x.AttributionConfidence
	}
	return 0
}

func (x *IncrementalRevenueRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *IncrementalRevenueRequest) GetSignalScores() map[string]float32 {
	if x != nil {
		return x.SignalScores
	}
	return nil
}

// IncrementalRevenueResponse confirms the attribution and fee calculation
type IncrementalRevenueResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Success              bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                                         // True if attributed and fee calculated
	CountedAsIncremental bool                   `protobuf:"varint,2,opt,name=counted_as_incremental,json=countedAsIncremental,proto3" json:"counted_as_incremental,omitempty"` // True if above baseline
	SuccessFeeAmount     *Money                 `protobuf:"bytes,3,opt,name=success_fee_amount,json=successFeeAmount,proto3" json:"success_fee_amount,omitempty"`              // 20% of incremental revenue
	LedgerEntryId        int32                  `protobuf:"varint,4,opt,name=ledger_entry_id,json=ledgerEntryId,proto3" json:"ledger_entry_id,omitempty"`                      // Immutable ledger entry ID
	InvoiceId            string                 `protobuf:"bytes,5,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`                                     // Invoice ID (set later when monthly invoice generated)
	Explanation          string                 `protobuf:"bytes,6,opt,name=explanation,proto3" json:"explanation,omitempty"`                                                  // XAI: "This order was $30 above your $69.99 baseline, with 85% confidence. Fee: $6.00"
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *IncrementalRevenueResponse) Reset() {
	*x = IncrementalRevenueResponse{}
	mi := &file_syncledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementalRevenueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementalRevenueResponse) ProtoMessage() {}

func (x *IncrementalRevenueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementalRevenueResponse.ProtoReflect.Descriptor instead.
func (*IncrementalRevenueResponse) Descriptor() ([]byte, []int) {
	return file_syncledger_proto_rawDescGZIP(), []int{2}
}

func (x *IncrementalRevenueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IncrementalRevenueResponse) GetCountedAsIncremental() bool {
	if x != nil {
		return x.CountedAsIncremental
	}
	return false
}

func (x *IncrementalRevenueResponse) GetSuccessFeeAmount() *Money {
	if x != nil {
		return x.SuccessFeeAmount
	}
	return nil
}

func (x *IncrementalRevenueResponse) GetLedgerEntryId() int32 {
	if x != nil {
		return x.LedgerEntryId
	}
	return 0
}

func (x *IncrementalRevenueResponse) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *IncrementalRevenueResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

// SuccessFeeRequest requests the monthly settlement report
type SuccessFeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       int32                  `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"` // Shopify store ID
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`                      // e.g., 2025
	Month         int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`                    // 1-12
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessFeeRequest) Reset() {
	*x = SuccessFeeRequest{}
	mi := &file_syncledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessFeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessFeeRequest) ProtoMessage() {}

func (x *SuccessFeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessFeeRequest.ProtoReflect.Descriptor instead.
func (*SuccessFeeRequest) Descriptor() ([]byte, []int) {
	return file_syncledger_proto_rawDescGZIP(), []int{3}
}

func (x *SuccessFeeRequest) GetStoreId() int32 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *SuccessFeeRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *SuccessFeeRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

// SuccessFeeResponse returns the monthly settlement calculations
type SuccessFeeResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Success              bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BaselineRevenue      *Money                 `protobuf:"bytes,2,opt,name=baseline_revenue,json=baselineRevenue,proto3" json:"baseline_revenue,omitempty"`                                                                               // Historical monthly average (pre-KIKI)
	CurrentRevenue       *Money                 `protobuf:"bytes,3,opt,name=current_revenue,json=currentRevenue,proto3" json:"current_revenue,omitempty"`                                                                                  // Actual revenue this month (with KIKI)
	IncrementalRevenue   *Money                 `protobuf:"bytes,4,opt,name=incremental_revenue,json=incrementalRevenue,proto3" json:"incremental_revenue,omitempty"`                                                                      // current - baseline
	GrowthPercentage     float32                `protobuf:"fixed32,5,opt,name=growth_percentage,json=growthPercentage,proto3" json:"growth_percentage,omitempty"`                                                                          // ((current - baseline) / baseline) * 100
	SuccessFeeAmount     *Money                 `protobuf:"bytes,6,opt,name=success_fee_amount,json=successFeeAmount,proto3" json:"success_fee_amount,omitempty"`                                                                          // 20% of incremental_revenue
	TotalOrdersReviewed  int32                  `protobuf:"varint,7,opt,name=total_orders_reviewed,json=totalOrdersReviewed,proto3" json:"total_orders_reviewed,omitempty"`                                                                // Total orders processed
	AttributedOrderCount int32                  `protobuf:"varint,8,opt,name=attributed_order_count,json=attributedOrderCount,proto3" json:"attributed_order_count,omitempty"`                                                             // Orders attributed to KIKI
	AttributionStats     map[string]int32       `protobuf:"bytes,9,rep,name=attribution_stats,json=attributionStats,proto3" json:"attribution_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // XAI: {"total_orders": 1234, "attributed": 456, "high_confidence": 234}
	HighConfidenceCount  int32                  `protobuf:"varint,10,opt,name=high_confidence_count,json=highConfidenceCount,proto3" json:"high_confidence_count,omitempty"`                                                               // Orders with confidence >= 0.85
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SuccessFeeResponse) Reset() {
	*x = SuccessFeeResponse{}
	mi := &file_syncledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessFeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessFeeResponse) ProtoMessage() {}

func (x *SuccessFeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessFeeResponse.ProtoReflect.Descriptor instead.
func (*SuccessFeeResponse) Descriptor() ([]byte, []int) {
	return file_syncledger_proto_rawDescGZIP(), []int{4}
}

func (x *SuccessFeeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SuccessFeeResponse) GetBaselineRevenue() *Money {
	if x != nil {
		return x.BaselineRevenue
	}
	return nil
}

func (x *SuccessFeeResponse) GetCurrentRevenue() *Money {
	if x != nil {
		return x.CurrentRevenue
	}
	return nil
}

func (x *SuccessFeeResponse) GetIncrementalRevenue() *Money {
	if x != nil {
		return x.IncrementalRevenue
	}
	return nil
}

func (x *SuccessFeeResponse) GetGrowthPercentage() float32 {
	if x != nil {
		return x.GrowthPercentage
	}
	return 0
}

func (x *SuccessFeeResponse) GetSuccessFeeAmount() *Money {
	if x != nil {
		return x.SuccessFeeAmount
	}
	return nil
}

func (x *SuccessFeeResponse) GetTotalOrdersReviewed() int32 {
	if x != nil {
		return x.TotalOrdersReviewed
	}
	return 0
}

func (x *SuccessFeeResponse) GetAttributedOrderCount() int32 {
	if x != nil {
		return x.AttributedOrderCount
	}
	return 0
}

func (x *SuccessFeeResponse) GetAttributionStats() map[string]int32 {
	if x != nil {
		return x.AttributionStats
	}
	return nil
}

func (x *SuccessFeeResponse) GetHighConfidenceCount() int32 {
	if x != nil {
		return x.HighConfidenceCount
	}
	return 0
}

// OrderAttributionRequest requests the attribution details for a specific order
type OrderAttributionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // Internal order ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderAttributionRequest) Reset() {
	*x = OrderAttributionRequest{}
	mi := &file_syncledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderAttributionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAttributionRequest) ProtoMessage() {}

func (x *OrderAttributionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAttributionRequest.ProtoReflect.Descriptor instead.
func (*OrderAttributionRequest) Descriptor() ([]byte, []int) {
	return file_syncledger_proto_rawDescGZIP(), []int{5}
}

func (x *OrderAttributionRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

// OrderAttributionResponse returns the XAI explanation for an order
type OrderAttributionResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Success               bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Attributed            bool                   `protobuf:"varint,2,opt,name=attributed,proto3" json:"attributed,omitempty"`                                                   // True if attributed to KIKI
	Confidence            float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`                                                  // Attribution confidence score
	IncrementalRevenue    *Money                 `protobuf:"bytes,4,opt,name=incremental_revenue,json=incrementalRevenue,proto3" json:"incremental_revenue,omitempty"`          // Amount above baseline
	SuccessFeeAmount      *Money                 `protobuf:"bytes,5,opt,name=success_fee_amount,json=successFeeAmount,proto3" json:"success_fee_amount,omitempty"`              // 20% of incremental
	Explanation           string                 `protobuf:"bytes,6,opt,name=explanation,proto3" json:"explanation,omitempty"`                                                  // Human-readable XAI explanation
	ContributingAgents    string                 `protobuf:"bytes,7,opt,name=contributing_agents,json=contributingAgents,proto3" json:"contributing_agents,omitempty"`          // JSON: {"SyncFlow": 0.5, "SyncCreate": 0.3, "SyncEngage": 0.2}
	CounterfactualRevenue *Money                 `protobuf:"bytes,8,opt,name=counterfactual_revenue,json=counterfactualRevenue,proto3" json:"counterfactual_revenue,omitempty"` // Estimated revenue without KIKI
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *OrderAttributionResponse) Reset() {
	*x = OrderAttributionResponse{}
	mi := &file_syncledger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderAttributionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAttributionResponse) ProtoMessage() {}

func (x *OrderAttributionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncledger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAttributionResponse.ProtoReflect.Descriptor instead.
func (*OrderAttributionResponse) Descriptor() ([]byte, []int) {
	return file_syncledger_proto_rawDescGZIP(), []int{6}
}

func (x *OrderAttributionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OrderAttributionResponse) GetAttributed() bool {
	if x != nil {
		return x.Attributed
	}
	return false
}

func (x *OrderAttributionResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *OrderAttributionResponse) GetIncrementalRevenue() *Money {
	if x != nil {
		return x.IncrementalRevenue
	}
	return nil
}

func (x *OrderAttributionResponse) GetSuccessFeeAmount() *Money {
	if x != nil {
		return x.SuccessFeeAmount
	}
	return nil
}

func (x *OrderAttributionResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *OrderAttributionResponse) GetContributingAgents() string {
	if x != nil {
		return x.ContributingAgents
	}
	return ""
}

func (x *OrderAttributionResponse) GetCounterfactualRevenue() *Money {
	if x != nil {
		return x.CounterfactualRevenue
	}
	return nil
}

// BaselineUpdateRequest updates the baseline metrics for a store
type BaselineUpdateRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	StoreId               int32                  `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`                                                // Shopify store ID
	BaselineRevenue       *Money                 `protobuf:"bytes,2,opt,name=baseline_revenue,json=baselineRevenue,proto3" json:"baseline_revenue,omitempty"`                         // Historical monthly average
	BaselineAvgOrderValue float32                `protobuf:"fixed32,3,opt,name=baseline_avg_order_value,json=baselineAvgOrderValue,proto3" json:"baseline_avg_order_value,omitempty"` // Historical AOV
	BaselineOrderCount    int32                  `protobuf:"varint,4,opt,name=baseline_order_count,json=baselineOrderCount,proto3" json:"baseline_order_count,omitempty"`             // Historical monthly order count
	CalculationMethod     string                 `protobuf:"bytes,5,opt,name=calculation_method,json=calculationMethod,proto3" json:"calculation_method,omitempty"`                   // "manual", "onboarding_90day", "rolling_90day"
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BaselineUpdateRequest) Reset() {
	*x = BaselineUpdateRequest{}
	mi := &file_syncledger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaselineUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaselineUpdateRequest) ProtoMessage() {}

func (x *BaselineUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncledger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaselineUpdateRequest.ProtoReflect.Descriptor instead.
func (*BaselineUpdateRequest) Descriptor() ([]byte, []int) {
	return file_syncledger_proto_rawDescGZIP(), []int{7}
}

func (x *BaselineUpdateRequest) GetStoreId() int32 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *BaselineUpdateRequest) GetBaselineRevenue() *Money {
	if x != nil {
		return x.BaselineRevenue
	}
	return nil
}

func (x *BaselineUpdateRequest) GetBaselineAvgOrderValue() float32 {
	if x != nil {
		return x.BaselineAvgOrderValue
	}
	return 0
}

func (x *BaselineUpdateRequest) GetBaselineOrderCount() int32 {
	if x != nil {
		return x.BaselineOrderCount
	}
	return 0
}

func (x *BaselineUpdateRequest) GetCalculationMethod() string {
	if x != nil {
		return x.CalculationMethod
	}
	return ""
}

// BaselineUpdateResponse confirms the baseline update
type BaselineUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BaselineId    int32                  `protobuf:"varint,2,opt,name=baseline_id,json=baselineId,proto3" json:"baseline_id,omitempty"` // Baseline snapshot ID
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                          // "Baseline updated successfully"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaselineUpdateResponse) Reset() {
	*x = BaselineUpdateResponse{}
	mi := &file_syncledger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaselineUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaselineUpdateResponse) ProtoMessage() {}

func (x *BaselineUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncledger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaselineUpdateResponse.ProtoReflect.Descriptor instead.
func (*BaselineUpdateResponse) Descriptor() ([]byte, []int) {
	return file_syncledger_proto_rawDescGZIP(), []int{8}
}

func (x *BaselineUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BaselineUpdateResponse) GetBaselineId() int32 {
	if x != nil {
		return x.BaselineId
	}
	return 0
}

func (x *BaselineUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_syncledger_proto protoreflect.FileDescriptor

const file_syncledger_proto_rawDesc = "" +
	"\n" +
	"\x10syncledger.proto\x12\n" +
	"syncledger\"O\n" +
	"\x05Money\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12\x14\n" +
	"\x05units\x18\x02 \x01(\x03R\x05units\x12\x14\n" +
	"\x05nanos\x18\x03 \x01(\x05R\x05nanos\"\x88\x04\n" +
	"\x19IncrementalRevenueRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\x05R\astoreId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderId\x12*\n" +
	"\x11platform_order_id\x18\x03 \x01(\tR\x0fplatformOrderId\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x124\n" +
	"\forder_amount\x18\x05 \x01(\v2\x11.syncledger.MoneyR\vorderAmount\x12@\n" +
	"\x12incremental_amount\x18\x06 \x01(\v2\x11.syncledger.MoneyR\x11incrementalAmount\x125\n" +
	"\x16attribution_confidence\x18\a \x01(\x02R\x15attributionConfidence\x12\x1f\n" +
	"\vcampaign_id\x18\b \x01(\tR\n" +
	"campaignId\x12\\\n" +
	"\rsignal_scores\x18\t \x03(\v27.syncledger.IncrementalRevenueRequest.SignalScoresEntryR\fsignalScores\x1a?\n" +
	"\x11SignalScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"\x96\x02\n" +
	"\x1aIncrementalRevenueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x124\n" +
	"\x16counted_as_incremental\x18\x02 \x01(\bR\x14countedAsIncremental\x12?\n" +
	"\x12success_fee_amount\x18\x03 \x01(\v2\x11.syncledger.MoneyR\x10successFeeAmount\x12&\n" +
	"\x0fledger_entry_id\x18\x04 \x01(\x05R\rledgerEntryId\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x05 \x01(\tR\tinvoiceId\x12 \n" +
	"\vexplanation\x18\x06 \x01(\tR\vexplanation\"X\n" +
	"\x11SuccessFeeRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\x05R\astoreId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\x05R\x05month\"\xa0\x05\n" +
	"\x12SuccessFeeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12<\n" +
	"\x10baseline_revenue\x18\x02 \x01(\v2\x11.syncledger.MoneyR\x0fbaselineRevenue\x12:\n" +
	"\x0fcurrent_revenue\x18\x03 \x01(\v2\x11.syncledger.MoneyR\x0ecurrentRevenue\x12B\n" +
	"\x13incremental_revenue\x18\x04 \x01(\v2\x11.syncledger.MoneyR\x12incrementalRevenue\x12+\n" +
	"\x11growth_percentage\x18\x05 \x01(\x02R\x10growthPercentage\x12?\n" +
	"\x12success_fee_amount\x18\x06 \x01(\v2\x11.syncledger.MoneyR\x10successFeeAmount\x122\n" +
	"\x15total_orders_reviewed\x18\a \x01(\x05R\x13totalOrdersReviewed\x124\n" +
	"\x16attributed_order_count\x18\b \x01(\x05R\x14attributedOrderCount\x12a\n" +
	"\x11attribution_stats\x18\t \x03(\v24.syncledger.SuccessFeeResponse.AttributionStatsEntryR\x10attributionStats\x122\n" +
	"\x15high_confidence_count\x18\n" +
	" \x01(\x05R\x13highConfidenceCount\x1aC\n" +
	"\x15AttributionStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"4\n" +
	"\x17OrderAttributionRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\"\x96\x03\n" +
	"\x18OrderAttributionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1e\n" +
	"\n" +
	"attributed\x18\x02 \x01(\bR\n" +
	"attributed\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12B\n" +
	"\x13incremental_revenue\x18\x04 \x01(\v2\x11.syncledger.MoneyR\x12incrementalRevenue\x12?\n" +
	"\x12success_fee_amount\x18\x05 \x01(\v2\x11.syncledger.MoneyR\x10successFeeAmount\x12 \n" +
	"\vexplanation\x18\x06 \x01(\tR\vexplanation\x12/\n" +
	"\x13contributing_agents\x18\a \x01(\tR\x12contributingAgents\x12H\n" +
	"\x16counterfactual_revenue\x18\b \x01(\v2\x11.syncledger.MoneyR\x15counterfactualRevenue\"\x8a\x02\n" +
	"\x15BaselineUpdateRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\x05R\astoreId\x12<\n" +
	"\x10baseline_revenue\x18\x02 \x01(\v2\x11.syncledger.MoneyR\x0fbaselineRevenue\x127\n" +
	"\x18baseline_avg_order_value\x18\x03 \x01(\x02R\x15baselineAvgOrderValue\x120\n" +
	"\x14baseline_order_count\x18\x04 \x01(\x05R\x12baselineOrderCount\x12-\n" +
	"\x12calculation_method\x18\x05 \x01(\tR\x11calculationMethod\"m\n" +
	"\x16BaselineUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vbaseline_id\x18\x02 \x01(\x05R\n" +
	"baselineId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\x96\x03\n" +
	"\x11SyncLedgerService\x12i\n" +
	"\x18RecordIncrementalRevenue\x12%.syncledger.IncrementalRevenueRequest\x1a&.syncledger.IncrementalRevenueResponse\x12T\n" +
	"\x13CalculateSuccessFee\x12\x1d.syncledger.SuccessFeeRequest\x1a\x1e.syncledger.SuccessFeeResponse\x12`\n" +
	"\x13GetOrderAttribution\x12#.syncledger.OrderAttributionRequest\x1a$.syncledger.OrderAttributionResponse\x12^\n" +
	"\x15UpdateBaselineMetrics\x12!.syncledger.BaselineUpdateRequest\x1a\".syncledger.BaselineUpdateResponseB\x12Z\x10syncledger/protob\x06proto3"

var (
	file_syncledger_proto_rawDescOnce sync.Once
	file_syncledger_proto_rawDescData []byte
)

func file_syncledger_proto_rawDescGZIP() []byte {
	file_syncledger_proto_rawDescOnce.Do(func() {
		file_syncledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_syncledger_proto_rawDesc), len(file_syncledger_proto_rawDesc)))
	})
	return file_syncledger_proto_rawDescData
}

var file_syncledger_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_syncledger_proto_goTypes = []any{
	(*Money)(nil),                      // 0: syncledger.Money
	(*IncrementalRevenueRequest)(nil),  // 1: syncledger.IncrementalRevenueRequest
	(*IncrementalRevenueResponse)(nil), // 2: syncledger.IncrementalRevenueResponse
	(*SuccessFeeRequest)(nil),          // 3: syncledger.SuccessFeeRequest
	(*SuccessFeeResponse)(nil),         // 4: syncledger.SuccessFeeResponse
	(*OrderAttributionRequest)(nil),    // 5: syncledger.OrderAttributionRequest
	(*OrderAttributionResponse)(nil),   // 6: syncledger.OrderAttributionResponse
	(*BaselineUpdateRequest)(nil),      // 7: syncledger.BaselineUpdateRequest
	(*BaselineUpdateResponse)(nil),     // 8: syncledger.BaselineUpdateResponse
	nil,                                // 9: syncledger.IncrementalRevenueRequest.SignalScoresEntry
	nil,                                // 10: syncledger.SuccessFeeResponse.AttributionStatsEntry
}
var file_syncledger_proto_depIdxs = []int32{
	0,  // 0: syncledger.IncrementalRevenueRequest.order_amount:type_name -> syncledger.Money
	0,  // 1: syncledger.IncrementalRevenueRequest.incremental_amount:type_name -> syncledger.Money
	9,  // 2: syncledger.IncrementalRevenueRequest.signal_scores:type_name -> syncledger.IncrementalRevenueRequest.SignalScoresEntry
	0,  // 3: syncledger.IncrementalRevenueResponse.success_fee_amount:type_name -> syncledger.Money
	0,  // 4: syncledger.SuccessFeeResponse.baseline_revenue:type_name -> syncledger.Money
	0,  // 5: syncledger.SuccessFeeResponse.current_revenue:type_name -> syncledger.Money
	0,  // 6: syncledger.SuccessFeeResponse.incremental_revenue:type_name -> syncledger.Money
	0,  // 7: syncledger.SuccessFeeResponse.success_fee_amount:type_name -> syncledger.Money
	10, // 8: syncledger.SuccessFeeResponse.attribution_stats:type_name -> syncledger.SuccessFeeResponse.AttributionStatsEntry
	0,  // 9: syncledger.OrderAttributionResponse.incremental_revenue:type_name -> syncledger.Money
	0,  // 10: syncledger.OrderAttributionResponse.success_fee_amount:type_name -> syncledger.Money
	0,  // 11: syncledger.OrderAttributionResponse.counterfactual_revenue:type_name -> syncledger.Money
	0,  // 12: syncledger.BaselineUpdateRequest.baseline_revenue:type_name -> syncledger.Money
	1,  // 13: syncledger.SyncLedgerService.RecordIncrementalRevenue:input_type -> syncledger.IncrementalRevenueRequest
	3,  // 14: syncledger.SyncLedgerService.CalculateSuccessFee:input_type -> syncledger.SuccessFeeRequest
	5,  // 15: syncledger.SyncLedgerService.GetOrderAttribution:input_type -> syncledger.OrderAttributionRequest
	7,  // 16: syncledger.SyncLedgerService.UpdateBaselineMetrics:input_type -> syncledger.BaselineUpdateRequest
	2,  // 17: syncledger.SyncLedgerService.RecordIncrementalRevenue:output_type -> syncledger.IncrementalRevenueResponse
	4,  // 18: syncledger.SyncLedgerService.CalculateSuccessFee:output_type -> syncledger.SuccessFeeResponse
	6,  // 19: syncledger.SyncLedgerService.GetOrderAttribution:output_type -> syncledger.OrderAttributionResponse
	8,  // 20: syncledger.SyncLedgerService.UpdateBaselineMetrics:output_type -> syncledger.BaselineUpdateResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_syncledger_proto_init() }
func file_syncledger_proto_init() {
	if File_syncledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_syncledger_proto_rawDesc), len(file_syncledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_syncledger_proto_goTypes,
		DependencyIndexes: file_syncledger_proto_depIdxs,
		MessageInfos:      file_syncledger_proto_msgTypes,
	}.Build()
	File_syncledger_proto = out.File
	file_syncledger_proto_goTypes = nil
	file_syncledger_proto_depIdxs = nil
}
