// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: syncledger.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncLedgerService_RecordIncrementalRevenue_FullMethodName = "/syncledger.SyncLedgerService/RecordIncrementalRevenue"
	SyncLedgerService_CalculateSuccessFee_FullMethodName      = "/syncledger.SyncLedgerService/CalculateSuccessFee"
	SyncLedgerService_GetOrderAttribution_FullMethodName      = "/syncledger.SyncLedgerService/GetOrderAttribution"
	SyncLedgerService_UpdateBaselineMetrics_FullMethodName    = "/syncledger.SyncLedgerService/UpdateBaselineMetrics"
)

// SyncLedgerServiceClient is the client API for SyncLedgerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// # SyncLedger™ - Automated OaaS Revenue Auditor
//
// REST equivalent: N/A (gRPC only for internal service communication)
// Called by: SyncPortal, SyncBill, Admin Dashboard
//
// Responsibilities:
// - Record incremental revenue attributions
// - Calculate monthly success fees (20% of uplift)
// - Provide XAI explainability for attributions
// - Generate immutable audit trails
type SyncLedgerServiceClient interface {
	// RecordIncrementalRevenue is called when SyncPortal attributes an order to KIKI
	//
	// Flow:
	// 1. SyncPortal webhook receives order from Shopify/WooCommerce
	// 2. Attribution engine calculates confidence (e.g., 0.85)
	// 3. If confidence >= 0.70, call this method
	// 4. SyncLedger records entry and calculates success fee
	//
	// Example:
	// Request: {store_id: 123, order_id: 456, amount: $99.99, confidence: 0.85}
	// Response: {success: true, fee: $5.99, incremental: $29.99}
	RecordIncrementalRevenue(ctx context.Context, in *IncrementalRevenueRequest, opts ...grpc.CallOption) (*IncrementalRevenueResponse, error)
	// CalculateSuccessFee generates the monthly OaaS settlement report
	//
	// Called by:
	// - SyncPortal dashboard (end of month)
	// - Admin invoice generation script
	// - Client API for transparency
	//
	// Returns:
	// - Baseline vs current revenue comparison
	// - Total incremental revenue
	// - Success fee (20% of incremental)
	// - Attribution breakdown (XAI)
	CalculateSuccessFee(ctx context.Context, in *SuccessFeeRequest, opts ...grpc.CallOption) (*SuccessFeeResponse, error)
	// GetOrderAttribution retrieves the attribution details for a specific order
	//
	// Used by:
	// - Client dashboard ("Why was I charged for this order?")
	// - Admin review panel
	// - XAI explainability reports
	GetOrderAttribution(ctx context.Context, in *OrderAttributionRequest, opts ...grpc.CallOption) (*OrderAttributionResponse, error)
	// UpdateBaselineMetrics updates the baseline snapshot for a store
	//
	// Called by:
	// - Onboarding (set initial baseline from pre-KIKI data)
	// - Monthly recalculation (rolling 90-day average)
	// - Admin override (manual adjustment)
	UpdateBaselineMetrics(ctx context.Context, in *BaselineUpdateRequest, opts ...grpc.CallOption) (*BaselineUpdateResponse, error)
}

type syncLedgerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncLedgerServiceClient(cc grpc.ClientConnInterface) SyncLedgerServiceClient {
	return &syncLedgerServiceClient{cc}
}

func (c *syncLedgerServiceClient) RecordIncrementalRevenue(ctx context.Context, in *IncrementalRevenueRequest, opts ...grpc.CallOption) (*IncrementalRevenueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncrementalRevenueResponse)
	err := c.cc.Invoke(ctx, SyncLedgerService_RecordIncrementalRevenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncLedgerServiceClient) CalculateSuccessFee(ctx context.Context, in *SuccessFeeRequest, opts ...grpc.CallOption) (*SuccessFeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessFeeResponse)
	err := c.cc.Invoke(ctx, SyncLedgerService_CalculateSuccessFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncLedgerServiceClient) GetOrderAttribution(ctx context.Context, in *OrderAttributionRequest, opts ...grpc.CallOption) (*OrderAttributionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderAttributionResponse)
	err := c.cc.Invoke(ctx, SyncLedgerService_GetOrderAttribution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncLedgerServiceClient) UpdateBaselineMetrics(ctx context.Context, in *BaselineUpdateRequest, opts ...grpc.CallOption) (*BaselineUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaselineUpdateResponse)
	err := c.cc.Invoke(ctx, SyncLedgerService_UpdateBaselineMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncLedgerServiceServer is the server API for SyncLedgerService service.
// All implementations must embed UnimplementedSyncLedgerServiceServer
// for forward compatibility.
//
// # SyncLedger™ - Automated OaaS Revenue Auditor
//
// REST equivalent: N/A (gRPC only for internal service communication)
// Called by: SyncPortal, SyncBill, Admin Dashboard
//
// Responsibilities:
// - Record incremental revenue attributions
// - Calculate monthly success fees (20% of uplift)
// - Provide XAI explainability for attributions
// - Generate immutable audit trails
type SyncLedgerServiceServer interface {
	// RecordIncrementalRevenue is called when SyncPortal attributes an order to KIKI
	//
	// Flow:
	// 1. SyncPortal webhook receives order from Shopify/WooCommerce
	// 2. Attribution engine calculates confidence (e.g., 0.85)
	// 3. If confidence >= 0.70, call this method
	// 4. SyncLedger records entry and calculates success fee
	//
	// Example:
	// Request: {store_id: 123, order_id: 456, amount: $99.99, confidence: 0.85}
	// Response: {success: true, fee: $5.99, incremental: $29.99}
	RecordIncrementalRevenue(context.Context, *IncrementalRevenueRequest) (*IncrementalRevenueResponse, error)
	// CalculateSuccessFee generates the monthly OaaS settlement report
	//
	// Called by:
	// - SyncPortal dashboard (end of month)
	// - Admin invoice generation script
	// - Client API for transparency
	//
	// Returns:
	// - Baseline vs current revenue comparison
	// - Total incremental revenue
	// - Success fee (20% of incremental)
	// - Attribution breakdown (XAI)
	CalculateSuccessFee(context.Context, *SuccessFeeRequest) (*SuccessFeeResponse, error)
	// GetOrderAttribution retrieves the attribution details for a specific order
	//
	// Used by:
	// - Client dashboard ("Why was I charged for this order?")
	// - Admin review panel
	// - XAI explainability reports
	GetOrderAttribution(context.Context, *OrderAttributionRequest) (*OrderAttributionResponse, error)
	// UpdateBaselineMetrics updates the baseline snapshot for a store
	//
	// Called by:
	// - Onboarding (set initial baseline from pre-KIKI data)
	// - Monthly recalculation (rolling 90-day average)
	// - Admin override (manual adjustment)
	UpdateBaselineMetrics(context.Context, *BaselineUpdateRequest) (*BaselineUpdateResponse, error)
	mustEmbedUnimplementedSyncLedgerServiceServer()
}

// UnimplementedSyncLedgerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncLedgerServiceServer struct{}

func (UnimplementedSyncLedgerServiceServer) RecordIncrementalRevenue(context.Context, *IncrementalRevenueRequest) (*IncrementalRevenueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordIncrementalRevenue not implemented")
}
func (UnimplementedSyncLedgerServiceServer) CalculateSuccessFee(context.Context, *SuccessFeeRequest) (*SuccessFeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateSuccessFee not implemented")
}
func (UnimplementedSyncLedgerServiceServer) GetOrderAttribution(context.Context, *OrderAttributionRequest) (*OrderAttributionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderAttribution not implemented")
}
func (UnimplementedSyncLedgerServiceServer) UpdateBaselineMetrics(context.Context, *BaselineUpdateRequest) (*BaselineUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBaselineMetrics not implemented")
}
func (UnimplementedSyncLedgerServiceServer) mustEmbedUnimplementedSyncLedgerServiceServer() {}
func (UnimplementedSyncLedgerServiceServer) testEmbeddedByValue()                           {}

// UnsafeSyncLedgerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncLedgerServiceServer will
// result in compilation errors.
type UnsafeSyncLedgerServiceServer interface {
	mustEmbedUnimplementedSyncLedgerServiceServer()
}

func RegisterSyncLedgerServiceServer(s grpc.ServiceRegistrar, srv SyncLedgerServiceServer) {
	// If the following call panics, it indicates UnimplementedSyncLedgerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncLedgerService_ServiceDesc, srv)
}

func _SyncLedgerService_RecordIncrementalRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementalRevenueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncLedgerServiceServer).RecordIncrementalRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncLedgerService_RecordIncrementalRevenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncLedgerServiceServer).RecordIncrementalRevenue(ctx, req.(*IncrementalRevenueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncLedgerService_CalculateSuccessFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuccessFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncLedgerServiceServer).CalculateSuccessFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncLedgerService_CalculateSuccessFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncLedgerServiceServer).CalculateSuccessFee(ctx, req.(*SuccessFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncLedgerService_GetOrderAttribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderAttributionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncLedgerServiceServer).GetOrderAttribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncLedgerService_GetOrderAttribution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncLedgerServiceServer).GetOrderAttribution(ctx, req.(*OrderAttributionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncLedgerService_UpdateBaselineMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaselineUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncLedgerServiceServer).UpdateBaselineMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncLedgerService_UpdateBaselineMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncLedgerServiceServer).UpdateBaselineMetrics(ctx, req.(*BaselineUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyncLedgerService_ServiceDesc is the grpc.ServiceDesc for SyncLedgerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncLedgerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "syncledger.SyncLedgerService",
	HandlerType: (*SyncLedgerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordIncrementalRevenue",
			Handler:    _SyncLedgerService_RecordIncrementalRevenue_Handler,
		},
		{
			MethodName: "CalculateSuccessFee",
			Handler:    _SyncLedgerService_CalculateSuccessFee_Handler,
		},
		{
			MethodName: "GetOrderAttribution",
			Handler:    _SyncLedgerService_GetOrderAttribution_Handler,
		},
		{
			MethodName: "UpdateBaselineMetrics",
			Handler:    _SyncLedgerService_UpdateBaselineMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "syncledger.proto",
}
