# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ltv_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ltv_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ltv_service.proto\x12\x03ltv\"\x8d\x01\n\x11PredictLtvRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x36\n\x08\x66\x65\x61tures\x18\x02 \x03(\x0b\x32$.ltv.PredictLtvRequest.FeaturesEntry\x1a/\n\rFeaturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"2\n\x12PredictLtvResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0b\n\x03ltv\x18\x02 \x01(\x02\x32K\n\nLtvService\x12=\n\nPredictLtv\x12\x16.ltv.PredictLtvRequest\x1a\x17.ltv.PredictLtvResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ltv_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTLTVREQUEST_FEATURESENTRY']._loaded_options = None
  _globals['_PREDICTLTVREQUEST_FEATURESENTRY']._serialized_options = b'8\001'
  _globals['_PREDICTLTVREQUEST']._serialized_start=27
  _globals['_PREDICTLTVREQUEST']._serialized_end=168
  _globals['_PREDICTLTVREQUEST_FEATURESENTRY']._serialized_start=121
  _globals['_PREDICTLTVREQUEST_FEATURESENTRY']._serialized_end=168
  _globals['_PREDICTLTVRESPONSE']._serialized_start=170
  _globals['_PREDICTLTVRESPONSE']._serialized_end=220
  _globals['_LTVSERVICE']._serialized_start=222
  _globals['_LTVSERVICE']._serialized_end=297
# @@protoc_insertion_point(module_scope)
