"""Initial schema with all KIKI models

Revision ID: 834c458d1fc5
Revises: 
Create Date: 2026-02-06 14:25:21.873419+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '834c458d1fc5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('deployment_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_deployment_id'), 'audit_logs', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('campaign_deployments',
    sa.Column('deployment_id', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('brand_name', sa.String(length=200), nullable=False),
    sa.Column('industry_category', sa.String(length=100), nullable=False),
    sa.Column('campaign_type', sa.Enum('ASC', 'ALC', 'AIC', name='campaigntype'), nullable=False),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('target_roi', sa.Float(), nullable=True),
    sa.Column('ltv_baseline', sa.Float(), nullable=False),
    sa.Column('max_cpa', sa.Float(), nullable=True),
    sa.Column('assets_source', sa.Enum('GENERATED', 'USER_PROVIDED', 'HYBRID', name='assetsource'), nullable=False),
    sa.Column('brand_safe', sa.Boolean(), nullable=True),
    sa.Column('compliance_status', sa.String(length=50), nullable=True),
    sa.Column('deployment_status', sa.Enum('DRAFT', 'DEPLOYED', 'ACTIVE', 'PAUSED', 'COMPLETED', 'FAILED', 'SAFETY_HOLD', name='deploymentstatus'), nullable=False),
    sa.Column('syncflow_deployment_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('deployment_id')
    )
    op.create_index(op.f('ix_campaign_deployments_brand_name'), 'campaign_deployments', ['brand_name'], unique=False)
    op.create_index(op.f('ix_campaign_deployments_created_at'), 'campaign_deployments', ['created_at'], unique=False)
    op.create_index(op.f('ix_campaign_deployments_deployment_id'), 'campaign_deployments', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_campaign_deployments_deployment_status'), 'campaign_deployments', ['deployment_status'], unique=False)
    op.create_index(op.f('ix_campaign_deployments_industry_category'), 'campaign_deployments', ['industry_category'], unique=False)
    op.create_table('daily_revenue_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('summary_date', sa.DateTime(), nullable=False),
    sa.Column('total_campaigns', sa.Integer(), nullable=True),
    sa.Column('active_campaigns', sa.Integer(), nullable=True),
    sa.Column('deployed_campaigns', sa.Integer(), nullable=True),
    sa.Column('total_spend', sa.Float(), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('total_conversions', sa.Integer(), nullable=True),
    sa.Column('avg_roi', sa.Float(), nullable=True),
    sa.Column('avg_cpa', sa.Float(), nullable=True),
    sa.Column('avg_ctr', sa.Float(), nullable=True),
    sa.Column('kiki_performance_fee', sa.Float(), nullable=True),
    sa.Column('kiki_clients_served', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_revenue_summary_summary_date'), 'daily_revenue_summary', ['summary_date'], unique=True)
    op.create_table('ltv_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('business_model', sa.String(length=50), nullable=True),
    sa.Column('predicted_ltv', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('predicted_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ltv_predictions_user_id'), 'ltv_predictions', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('meta_api_key', sa.Text(), nullable=True),
    sa.Column('google_api_key', sa.Text(), nullable=True),
    sa.Column('tiktok_api_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('ad_copies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deployment_id', sa.String(length=50), nullable=False),
    sa.Column('copy_text', sa.Text(), nullable=False),
    sa.Column('variation_number', sa.Integer(), nullable=False),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('audience_segment', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['campaign_deployments.deployment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_copies_deployment_id'), 'ad_copies', ['deployment_id'], unique=False)
    op.create_table('image_prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deployment_id', sa.String(length=50), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('aesthetic_score', sa.Float(), nullable=True),
    sa.Column('variation_number', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['campaign_deployments.deployment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_prompts_deployment_id'), 'image_prompts', ['deployment_id'], unique=False)
    op.create_table('performance_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deployment_id', sa.String(length=50), nullable=False),
    sa.Column('metric_date', sa.DateTime(), nullable=False),
    sa.Column('spend', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('cpa', sa.Float(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('predicted_ltv', sa.Float(), nullable=True),
    sa.Column('actual_ltv', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['campaign_deployments.deployment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_metrics_deployment_id'), 'performance_metrics', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_performance_metrics_metric_date'), 'performance_metrics', ['metric_date'], unique=False)
    op.create_table('platform_deployments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deployment_id', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.Enum('META', 'GOOGLE', 'TIKTOK', 'SNAPCHAT', 'PINTEREST', 'TWITTER', 'LINKEDIN', name='platform'), nullable=False),
    sa.Column('platform_campaign_id', sa.String(length=100), nullable=True),
    sa.Column('platform_status', sa.String(length=50), nullable=True),
    sa.Column('platform_config', sa.JSON(), nullable=True),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['campaign_deployments.deployment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_deployments_deployment_id'), 'platform_deployments', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_platform_deployments_platform'), 'platform_deployments', ['platform'], unique=False)
    op.create_table('user_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deployment_id', sa.String(length=50), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('asset_content', sa.Text(), nullable=False),
    sa.Column('asset_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['campaign_deployments.deployment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_assets_deployment_id'), 'user_assets', ['deployment_id'], unique=False)
    op.create_table('video_prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deployment_id', sa.String(length=50), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('camera_motion', sa.String(length=100), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('variation_number', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['campaign_deployments.deployment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_prompts_deployment_id'), 'video_prompts', ['deployment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_prompts_deployment_id'), table_name='video_prompts')
    op.drop_table('video_prompts')
    op.drop_index(op.f('ix_user_assets_deployment_id'), table_name='user_assets')
    op.drop_table('user_assets')
    op.drop_index(op.f('ix_platform_deployments_platform'), table_name='platform_deployments')
    op.drop_index(op.f('ix_platform_deployments_deployment_id'), table_name='platform_deployments')
    op.drop_table('platform_deployments')
    op.drop_index(op.f('ix_performance_metrics_metric_date'), table_name='performance_metrics')
    op.drop_index(op.f('ix_performance_metrics_deployment_id'), table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_index(op.f('ix_image_prompts_deployment_id'), table_name='image_prompts')
    op.drop_table('image_prompts')
    op.drop_index(op.f('ix_ad_copies_deployment_id'), table_name='ad_copies')
    op.drop_table('ad_copies')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ltv_predictions_user_id'), table_name='ltv_predictions')
    op.drop_table('ltv_predictions')
    op.drop_index(op.f('ix_daily_revenue_summary_summary_date'), table_name='daily_revenue_summary')
    op.drop_table('daily_revenue_summary')
    op.drop_index(op.f('ix_campaign_deployments_industry_category'), table_name='campaign_deployments')
    op.drop_index(op.f('ix_campaign_deployments_deployment_status'), table_name='campaign_deployments')
    op.drop_index(op.f('ix_campaign_deployments_deployment_id'), table_name='campaign_deployments')
    op.drop_index(op.f('ix_campaign_deployments_created_at'), table_name='campaign_deployments')
    op.drop_index(op.f('ix_campaign_deployments_brand_name'), table_name='campaign_deployments')
    op.drop_table('campaign_deployments')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_deployment_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
