# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import value_pb2 as value__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in value_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LTVServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictLTV = channel.unary_unary(
                '/value.LTVService/PredictLTV',
                request_serializer=value__pb2.PredictLTVRequest.SerializeToString,
                response_deserializer=value__pb2.PredictLTVResponse.FromString,
                _registered_method=True)
        self.TrainLTV = channel.unary_unary(
                '/value.LTVService/TrainLTV',
                request_serializer=value__pb2.TrainLTVRequest.SerializeToString,
                response_deserializer=value__pb2.TrainLTVResponse.FromString,
                _registered_method=True)


class LTVServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PredictLTV(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainLTV(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LTVServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictLTV': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictLTV,
                    request_deserializer=value__pb2.PredictLTVRequest.FromString,
                    response_serializer=value__pb2.PredictLTVResponse.SerializeToString,
            ),
            'TrainLTV': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainLTV,
                    request_deserializer=value__pb2.TrainLTVRequest.FromString,
                    response_serializer=value__pb2.TrainLTVResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'value.LTVService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('value.LTVService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LTVService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictLTV(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/value.LTVService/PredictLTV',
            value__pb2.PredictLTVRequest.SerializeToString,
            value__pb2.PredictLTVResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrainLTV(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/value.LTVService/TrainLTV',
            value__pb2.TrainLTVRequest.SerializeToString,
            value__pb2.TrainLTVResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
