# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kiki_core.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kiki_core.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fkiki_core.proto\x12\x04kiki\"/\n\x0bPlanRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\t\",\n\x0cPlanResponse\x12\x0c\n\x04plan\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"0\n\x0b\x44\x61taRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08\x66\x65\x61tures\x18\x02 \x03(\x02\"/\n\tLTVResult\x12\x0b\n\x03ltv\x18\x01 \x01(\x02\x12\x15\n\rmodel_version\x18\x02 \x01(\t\"]\n\x17GenerateCreativeRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05style\x18\x03 \x01(\t\x12\x12\n\nnum_images\x18\x04 \x01(\x05\">\n\x18GenerateCreativeResponse\x12\x12\n\nimage_urls\x18\x01 \x03(\t\x12\x0e\n\x06job_id\x18\x02 \x01(\t2K\n\x14StrategyOrchestrator\x12\x33\n\nCoordinate\x12\x11.kiki.PlanRequest\x1a\x12.kiki.PlanResponse2?\n\x0bValueEngine\x12\x30\n\nPredictLTV\x12\x11.kiki.DataRequest\x1a\x0f.kiki.LTVResult2f\n\x11\x43reativeGenerator\x12Q\n\x10GenerateCreative\x12\x1d.kiki.GenerateCreativeRequest\x1a\x1e.kiki.GenerateCreativeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kiki_core_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLANREQUEST']._serialized_start=25
  _globals['_PLANREQUEST']._serialized_end=72
  _globals['_PLANRESPONSE']._serialized_start=74
  _globals['_PLANRESPONSE']._serialized_end=118
  _globals['_DATAREQUEST']._serialized_start=120
  _globals['_DATAREQUEST']._serialized_end=168
  _globals['_LTVRESULT']._serialized_start=170
  _globals['_LTVRESULT']._serialized_end=217
  _globals['_GENERATECREATIVEREQUEST']._serialized_start=219
  _globals['_GENERATECREATIVEREQUEST']._serialized_end=312
  _globals['_GENERATECREATIVERESPONSE']._serialized_start=314
  _globals['_GENERATECREATIVERESPONSE']._serialized_end=376
  _globals['_STRATEGYORCHESTRATOR']._serialized_start=378
  _globals['_STRATEGYORCHESTRATOR']._serialized_end=453
  _globals['_VALUEENGINE']._serialized_start=455
  _globals['_VALUEENGINE']._serialized_end=518
  _globals['_CREATIVEGENERATOR']._serialized_start=520
  _globals['_CREATIVEGENERATOR']._serialized_end=622
# @@protoc_insertion_point(module_scope)
