// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/simulation.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncTwinService_SimulateStrategy_FullMethodName = "/kiki.synctwin.SyncTwinService/SimulateStrategy"
	SyncTwinService_RunChaosTest_FullMethodName     = "/kiki.synctwin.SyncTwinService/RunChaosTest"
	SyncTwinService_MirrorSync_FullMethodName       = "/kiki.synctwin.SyncTwinService/MirrorSync"
)

// SyncTwinServiceClient is the client API for SyncTwinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyncTwinServiceClient interface {
	SimulateStrategy(ctx context.Context, in *SimulationRequest, opts ...grpc.CallOption) (*SimulationResult, error)
	// Chaos test for market shock scenarios
	RunChaosTest(ctx context.Context, in *SimulationRequest, opts ...grpc.CallOption) (*SimulationResult, error)
	// Real-to-Sim synchronization
	MirrorSync(ctx context.Context, in *SimulationRequest, opts ...grpc.CallOption) (*SimulationResult, error)
}

type syncTwinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncTwinServiceClient(cc grpc.ClientConnInterface) SyncTwinServiceClient {
	return &syncTwinServiceClient{cc}
}

func (c *syncTwinServiceClient) SimulateStrategy(ctx context.Context, in *SimulationRequest, opts ...grpc.CallOption) (*SimulationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimulationResult)
	err := c.cc.Invoke(ctx, SyncTwinService_SimulateStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncTwinServiceClient) RunChaosTest(ctx context.Context, in *SimulationRequest, opts ...grpc.CallOption) (*SimulationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimulationResult)
	err := c.cc.Invoke(ctx, SyncTwinService_RunChaosTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncTwinServiceClient) MirrorSync(ctx context.Context, in *SimulationRequest, opts ...grpc.CallOption) (*SimulationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimulationResult)
	err := c.cc.Invoke(ctx, SyncTwinService_MirrorSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncTwinServiceServer is the server API for SyncTwinService service.
// All implementations must embed UnimplementedSyncTwinServiceServer
// for forward compatibility.
type SyncTwinServiceServer interface {
	SimulateStrategy(context.Context, *SimulationRequest) (*SimulationResult, error)
	// Chaos test for market shock scenarios
	RunChaosTest(context.Context, *SimulationRequest) (*SimulationResult, error)
	// Real-to-Sim synchronization
	MirrorSync(context.Context, *SimulationRequest) (*SimulationResult, error)
	mustEmbedUnimplementedSyncTwinServiceServer()
}

// UnimplementedSyncTwinServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncTwinServiceServer struct{}

func (UnimplementedSyncTwinServiceServer) SimulateStrategy(context.Context, *SimulationRequest) (*SimulationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SimulateStrategy not implemented")
}
func (UnimplementedSyncTwinServiceServer) RunChaosTest(context.Context, *SimulationRequest) (*SimulationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RunChaosTest not implemented")
}
func (UnimplementedSyncTwinServiceServer) MirrorSync(context.Context, *SimulationRequest) (*SimulationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method MirrorSync not implemented")
}
func (UnimplementedSyncTwinServiceServer) mustEmbedUnimplementedSyncTwinServiceServer() {}
func (UnimplementedSyncTwinServiceServer) testEmbeddedByValue()                         {}

// UnsafeSyncTwinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncTwinServiceServer will
// result in compilation errors.
type UnsafeSyncTwinServiceServer interface {
	mustEmbedUnimplementedSyncTwinServiceServer()
}

func RegisterSyncTwinServiceServer(s grpc.ServiceRegistrar, srv SyncTwinServiceServer) {
	// If the following call panics, it indicates UnimplementedSyncTwinServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncTwinService_ServiceDesc, srv)
}

func _SyncTwinService_SimulateStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncTwinServiceServer).SimulateStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncTwinService_SimulateStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncTwinServiceServer).SimulateStrategy(ctx, req.(*SimulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncTwinService_RunChaosTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncTwinServiceServer).RunChaosTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncTwinService_RunChaosTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncTwinServiceServer).RunChaosTest(ctx, req.(*SimulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncTwinService_MirrorSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncTwinServiceServer).MirrorSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncTwinService_MirrorSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncTwinServiceServer).MirrorSync(ctx, req.(*SimulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyncTwinService_ServiceDesc is the grpc.ServiceDesc for SyncTwinService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncTwinService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kiki.synctwin.SyncTwinService",
	HandlerType: (*SyncTwinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SimulateStrategy",
			Handler:    _SyncTwinService_SimulateStrategy_Handler,
		},
		{
			MethodName: "RunChaosTest",
			Handler:    _SyncTwinService_RunChaosTest_Handler,
		},
		{
			MethodName: "MirrorSync",
			Handler:    _SyncTwinService_MirrorSync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/simulation.proto",
}
