// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/simulation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Simulation request for SyncTwin
type SimulationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyJson  string                 `protobuf:"bytes,1,opt,name=strategy_json,json=strategyJson,proto3" json:"strategy_json,omitempty"` // JSON-encoded campaign strategy
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"` // Target platform (meta, google, tiktok, etc.)
	Budget        float64                `protobuf:"fixed64,4,opt,name=budget,proto3" json:"budget,omitempty"`
	TargetLtv     float64                `protobuf:"fixed64,5,opt,name=target_ltv,json=targetLtv,proto3" json:"target_ltv,omitempty"`
	RoiThreshold  float64                `protobuf:"fixed64,6,opt,name=roi_threshold,json=roiThreshold,proto3" json:"roi_threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationRequest) Reset() {
	*x = SimulationRequest{}
	mi := &file_proto_simulation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationRequest) ProtoMessage() {}

func (x *SimulationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationRequest.ProtoReflect.Descriptor instead.
func (*SimulationRequest) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{0}
}

func (x *SimulationRequest) GetStrategyJson() string {
	if x != nil {
		return x.StrategyJson
	}
	return ""
}

func (x *SimulationRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SimulationRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SimulationRequest) GetBudget() float64 {
	if x != nil {
		return x.Budget
	}
	return 0
}

func (x *SimulationRequest) GetTargetLtv() float64 {
	if x != nil {
		return x.TargetLtv
	}
	return 0
}

func (x *SimulationRequest) GetRoiThreshold() float64 {
	if x != nil {
		return x.RoiThreshold
	}
	return 0
}

// Simulation result returned by SyncTwin
type SimulationResult struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ConfidenceScore          float64                `protobuf:"fixed64,1,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"` // 0.0-1.0
	RiskProfile              string                 `protobuf:"bytes,2,opt,name=risk_profile,json=riskProfile,proto3" json:"risk_profile,omitempty"`               // "conservative" | "moderate" | "aggressive"
	ProjectedNetProfitUplift float64                `protobuf:"fixed64,3,opt,name=projected_net_profit_uplift,json=projectedNetProfitUplift,proto3" json:"projected_net_profit_uplift,omitempty"`
	Reason                   string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Violations               []string               `protobuf:"bytes,5,rep,name=violations,proto3" json:"violations,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SimulationResult) Reset() {
	*x = SimulationResult{}
	mi := &file_proto_simulation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationResult) ProtoMessage() {}

func (x *SimulationResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationResult.ProtoReflect.Descriptor instead.
func (*SimulationResult) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{1}
}

func (x *SimulationResult) GetConfidenceScore() float64 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *SimulationResult) GetRiskProfile() string {
	if x != nil {
		return x.RiskProfile
	}
	return ""
}

func (x *SimulationResult) GetProjectedNetProfitUplift() float64 {
	if x != nil {
		return x.ProjectedNetProfitUplift
	}
	return 0
}

func (x *SimulationResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SimulationResult) GetViolations() []string {
	if x != nil {
		return x.Violations
	}
	return nil
}

var File_proto_simulation_proto protoreflect.FileDescriptor

const file_proto_simulation_proto_rawDesc = "" +
	"\n" +
	"\x16proto/simulation.proto\x12\rkiki.synctwin\"\xcd\x01\n" +
	"\x11SimulationRequest\x12#\n" +
	"\rstrategy_json\x18\x01 \x01(\tR\fstrategyJson\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x16\n" +
	"\x06budget\x18\x04 \x01(\x01R\x06budget\x12\x1d\n" +
	"\n" +
	"target_ltv\x18\x05 \x01(\x01R\ttargetLtv\x12#\n" +
	"\rroi_threshold\x18\x06 \x01(\x01R\froiThreshold\"\xd7\x01\n" +
	"\x10SimulationResult\x12)\n" +
	"\x10confidence_score\x18\x01 \x01(\x01R\x0fconfidenceScore\x12!\n" +
	"\frisk_profile\x18\x02 \x01(\tR\vriskProfile\x12=\n" +
	"\x1bprojected_net_profit_uplift\x18\x03 \x01(\x01R\x18projectedNetProfitUplift\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1e\n" +
	"\n" +
	"violations\x18\x05 \x03(\tR\n" +
	"violations2\x8c\x02\n" +
	"\x0fSyncTwinService\x12U\n" +
	"\x10SimulateStrategy\x12 .kiki.synctwin.SimulationRequest\x1a\x1f.kiki.synctwin.SimulationResult\x12Q\n" +
	"\fRunChaosTest\x12 .kiki.synctwin.SimulationRequest\x1a\x1f.kiki.synctwin.SimulationResult\x12O\n" +
	"\n" +
	"MirrorSync\x12 .kiki.synctwin.SimulationRequest\x1a\x1f.kiki.synctwin.SimulationResultB\x16Z\x14synctwin/proto;protob\x06proto3"

var (
	file_proto_simulation_proto_rawDescOnce sync.Once
	file_proto_simulation_proto_rawDescData []byte
)

func file_proto_simulation_proto_rawDescGZIP() []byte {
	file_proto_simulation_proto_rawDescOnce.Do(func() {
		file_proto_simulation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_simulation_proto_rawDesc), len(file_proto_simulation_proto_rawDesc)))
	})
	return file_proto_simulation_proto_rawDescData
}

var file_proto_simulation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_simulation_proto_goTypes = []any{
	(*SimulationRequest)(nil), // 0: kiki.synctwin.SimulationRequest
	(*SimulationResult)(nil),  // 1: kiki.synctwin.SimulationResult
}
var file_proto_simulation_proto_depIdxs = []int32{
	0, // 0: kiki.synctwin.SyncTwinService.SimulateStrategy:input_type -> kiki.synctwin.SimulationRequest
	0, // 1: kiki.synctwin.SyncTwinService.RunChaosTest:input_type -> kiki.synctwin.SimulationRequest
	0, // 2: kiki.synctwin.SyncTwinService.MirrorSync:input_type -> kiki.synctwin.SimulationRequest
	1, // 3: kiki.synctwin.SyncTwinService.SimulateStrategy:output_type -> kiki.synctwin.SimulationResult
	1, // 4: kiki.synctwin.SyncTwinService.RunChaosTest:output_type -> kiki.synctwin.SimulationResult
	1, // 5: kiki.synctwin.SyncTwinService.MirrorSync:output_type -> kiki.synctwin.SimulationResult
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_simulation_proto_init() }
func file_proto_simulation_proto_init() {
	if File_proto_simulation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_simulation_proto_rawDesc), len(file_proto_simulation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_simulation_proto_goTypes,
		DependencyIndexes: file_proto_simulation_proto_depIdxs,
		MessageInfos:      file_proto_simulation_proto_msgTypes,
	}.Build()
	File_proto_simulation_proto = out.File
	file_proto_simulation_proto_goTypes = nil
	file_proto_simulation_proto_depIdxs = nil
}
