// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: explainability_notification.proto

package explainabilitypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExplainabilityNotification struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventId          string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Timestamp        string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Agent            string                 `protobuf:"bytes,3,opt,name=agent,proto3" json:"agent,omitempty"`
	RecipientType    string                 `protobuf:"bytes,4,opt,name=recipient_type,json=recipientType,proto3" json:"recipient_type,omitempty"` // "client" or "admin"
	Reasoning        string                 `protobuf:"bytes,5,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	Observation      string                 `protobuf:"bytes,6,opt,name=observation,proto3" json:"observation,omitempty"`
	Action           string                 `protobuf:"bytes,7,opt,name=action,proto3" json:"action,omitempty"`
	Outcome          string                 `protobuf:"bytes,8,opt,name=outcome,proto3" json:"outcome,omitempty"`
	TechnicalDetails map[string]string      `protobuf:"bytes,9,rep,name=technical_details,json=technicalDetails,proto3" json:"technical_details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FinancialImpact  *FinancialImpact       `protobuf:"bytes,10,opt,name=financial_impact,json=financialImpact,proto3" json:"financial_impact,omitempty"`
	RecoveryPath     string                 `protobuf:"bytes,11,opt,name=recovery_path,json=recoveryPath,proto3" json:"recovery_path,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExplainabilityNotification) Reset() {
	*x = ExplainabilityNotification{}
	mi := &file_explainability_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainabilityNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainabilityNotification) ProtoMessage() {}

func (x *ExplainabilityNotification) ProtoReflect() protoreflect.Message {
	mi := &file_explainability_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainabilityNotification.ProtoReflect.Descriptor instead.
func (*ExplainabilityNotification) Descriptor() ([]byte, []int) {
	return file_explainability_notification_proto_rawDescGZIP(), []int{0}
}

func (x *ExplainabilityNotification) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ExplainabilityNotification) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ExplainabilityNotification) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *ExplainabilityNotification) GetRecipientType() string {
	if x != nil {
		return x.RecipientType
	}
	return ""
}

func (x *ExplainabilityNotification) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *ExplainabilityNotification) GetObservation() string {
	if x != nil {
		return x.Observation
	}
	return ""
}

func (x *ExplainabilityNotification) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ExplainabilityNotification) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *ExplainabilityNotification) GetTechnicalDetails() map[string]string {
	if x != nil {
		return x.TechnicalDetails
	}
	return nil
}

func (x *ExplainabilityNotification) GetFinancialImpact() *FinancialImpact {
	if x != nil {
		return x.FinancialImpact
	}
	return nil
}

func (x *ExplainabilityNotification) GetRecoveryPath() string {
	if x != nil {
		return x.RecoveryPath
	}
	return ""
}

type FinancialImpact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EstimatedRoi  float64                `protobuf:"fixed64,1,opt,name=estimated_roi,json=estimatedRoi,proto3" json:"estimated_roi,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinancialImpact) Reset() {
	*x = FinancialImpact{}
	mi := &file_explainability_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinancialImpact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinancialImpact) ProtoMessage() {}

func (x *FinancialImpact) ProtoReflect() protoreflect.Message {
	mi := &file_explainability_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinancialImpact.ProtoReflect.Descriptor instead.
func (*FinancialImpact) Descriptor() ([]byte, []int) {
	return file_explainability_notification_proto_rawDescGZIP(), []int{1}
}

func (x *FinancialImpact) GetEstimatedRoi() float64 {
	if x != nil {
		return x.EstimatedRoi
	}
	return 0
}

func (x *FinancialImpact) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_explainability_notification_proto protoreflect.FileDescriptor

const file_explainability_notification_proto_rawDesc = "" +
	"\n" +
	"!explainability_notification.proto\x12\x0eexplainability\"\xa9\x04\n" +
	"\x1aExplainabilityNotification\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05agent\x18\x03 \x01(\tR\x05agent\x12%\n" +
	"\x0erecipient_type\x18\x04 \x01(\tR\rrecipientType\x12\x1c\n" +
	"\treasoning\x18\x05 \x01(\tR\treasoning\x12 \n" +
	"\vobservation\x18\x06 \x01(\tR\vobservation\x12\x16\n" +
	"\x06action\x18\a \x01(\tR\x06action\x12\x18\n" +
	"\aoutcome\x18\b \x01(\tR\aoutcome\x12m\n" +
	"\x11technical_details\x18\t \x03(\v2@.explainability.ExplainabilityNotification.TechnicalDetailsEntryR\x10technicalDetails\x12J\n" +
	"\x10financial_impact\x18\n" +
	" \x01(\v2\x1f.explainability.FinancialImpactR\x0ffinancialImpact\x12#\n" +
	"\rrecovery_path\x18\v \x01(\tR\frecoveryPath\x1aC\n" +
	"\x15TechnicalDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x0fFinancialImpact\x12#\n" +
	"\restimated_roi\x18\x01 \x01(\x01R\festimatedRoi\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrencyB?Z=github.com/kiki-agent/schemas/explainability;explainabilitypbb\x06proto3"

var (
	file_explainability_notification_proto_rawDescOnce sync.Once
	file_explainability_notification_proto_rawDescData []byte
)

func file_explainability_notification_proto_rawDescGZIP() []byte {
	file_explainability_notification_proto_rawDescOnce.Do(func() {
		file_explainability_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_explainability_notification_proto_rawDesc), len(file_explainability_notification_proto_rawDesc)))
	})
	return file_explainability_notification_proto_rawDescData
}

var file_explainability_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_explainability_notification_proto_goTypes = []any{
	(*ExplainabilityNotification)(nil), // 0: explainability.ExplainabilityNotification
	(*FinancialImpact)(nil),            // 1: explainability.FinancialImpact
	nil,                                // 2: explainability.ExplainabilityNotification.TechnicalDetailsEntry
}
var file_explainability_notification_proto_depIdxs = []int32{
	2, // 0: explainability.ExplainabilityNotification.technical_details:type_name -> explainability.ExplainabilityNotification.TechnicalDetailsEntry
	1, // 1: explainability.ExplainabilityNotification.financial_impact:type_name -> explainability.FinancialImpact
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_explainability_notification_proto_init() }
func file_explainability_notification_proto_init() {
	if File_explainability_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_explainability_notification_proto_rawDesc), len(file_explainability_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_explainability_notification_proto_goTypes,
		DependencyIndexes: file_explainability_notification_proto_depIdxs,
		MessageInfos:      file_explainability_notification_proto_msgTypes,
	}.Build()
	File_explainability_notification_proto = out.File
	file_explainability_notification_proto_goTypes = nil
	file_explainability_notification_proto_depIdxs = nil
}
