# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bidding_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bidding_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62idding_service.proto\x12\x07\x62idding\"B\n\nBidRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64_slot\x18\x02 \x01(\t\x12\x12\n\nbid_amount\x18\x03 \x01(\x02\"?\n\x0b\x42idResponse\x12\x0e\n\x06\x62id_id\x18\x01 \x01(\t\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x02 \x01(\x08\x12\x0e\n\x06reason\x18\x03 \x01(\t2I\n\x0e\x42iddingService\x12\x37\n\nExecuteBid\x12\x13.bidding.BidRequest\x1a\x14.bidding.BidResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bidding_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BIDREQUEST']._serialized_start=34
  _globals['_BIDREQUEST']._serialized_end=100
  _globals['_BIDRESPONSE']._serialized_start=102
  _globals['_BIDRESPONSE']._serialized_end=165
  _globals['_BIDDINGSERVICE']._serialized_start=167
  _globals['_BIDDINGSERVICE']._serialized_end=240
# @@protoc_insertion_point(module_scope)
