# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shield.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'shield.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cshield.proto\x12\x06shield\"\x89\x01\n\x0c\x41uditRequest\x12\r\n\x05\x65vent\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12,\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x1e.shield.AuditRequest.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\".\n\rAuditResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05\x65vent\x18\x02 \x01(\t\"o\n\x0fRiskScanRequest\x12/\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32!.shield.RiskScanRequest.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\"\n\x10RiskScanResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x88\x01\n\x11\x43omplianceService\x12\x34\n\x05\x41udit\x12\x14.shield.AuditRequest\x1a\x15.shield.AuditResponse\x12=\n\x08RiskScan\x12\x17.shield.RiskScanRequest\x1a\x18.shield.RiskScanResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shield_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDITREQUEST_DATAENTRY']._loaded_options = None
  _globals['_AUDITREQUEST_DATAENTRY']._serialized_options = b'8\001'
  _globals['_RISKSCANREQUEST_DATAENTRY']._loaded_options = None
  _globals['_RISKSCANREQUEST_DATAENTRY']._serialized_options = b'8\001'
  _globals['_AUDITREQUEST']._serialized_start=25
  _globals['_AUDITREQUEST']._serialized_end=162
  _globals['_AUDITREQUEST_DATAENTRY']._serialized_start=119
  _globals['_AUDITREQUEST_DATAENTRY']._serialized_end=162
  _globals['_AUDITRESPONSE']._serialized_start=164
  _globals['_AUDITRESPONSE']._serialized_end=210
  _globals['_RISKSCANREQUEST']._serialized_start=212
  _globals['_RISKSCANREQUEST']._serialized_end=323
  _globals['_RISKSCANREQUEST_DATAENTRY']._serialized_start=119
  _globals['_RISKSCANREQUEST_DATAENTRY']._serialized_end=162
  _globals['_RISKSCANRESPONSE']._serialized_start=325
  _globals['_RISKSCANRESPONSE']._serialized_end=359
  _globals['_COMPLIANCESERVICE']._serialized_start=362
  _globals['_COMPLIANCESERVICE']._serialized_end=498
# @@protoc_insertion_point(module_scope)
