# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import shield_pb2 as shield__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in shield_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ComplianceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Audit = channel.unary_unary(
                '/shield.ComplianceService/Audit',
                request_serializer=shield__pb2.AuditRequest.SerializeToString,
                response_deserializer=shield__pb2.AuditResponse.FromString,
                _registered_method=True)
        self.RiskScan = channel.unary_unary(
                '/shield.ComplianceService/RiskScan',
                request_serializer=shield__pb2.RiskScanRequest.SerializeToString,
                response_deserializer=shield__pb2.RiskScanResponse.FromString,
                _registered_method=True)


class ComplianceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Audit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RiskScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComplianceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Audit': grpc.unary_unary_rpc_method_handler(
                    servicer.Audit,
                    request_deserializer=shield__pb2.AuditRequest.FromString,
                    response_serializer=shield__pb2.AuditResponse.SerializeToString,
            ),
            'RiskScan': grpc.unary_unary_rpc_method_handler(
                    servicer.RiskScan,
                    request_deserializer=shield__pb2.RiskScanRequest.FromString,
                    response_serializer=shield__pb2.RiskScanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shield.ComplianceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shield.ComplianceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ComplianceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Audit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shield.ComplianceService/Audit',
            shield__pb2.AuditRequest.SerializeToString,
            shield__pb2.AuditResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RiskScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shield.ComplianceService/RiskScan',
            shield__pb2.RiskScanRequest.SerializeToString,
            shield__pb2.RiskScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
