// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: strategy_orchestrator.proto

package strategy_orchestratorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrchestrateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	UserIds       []string               `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrchestrateRequest) Reset() {
	*x = OrchestrateRequest{}
	mi := &file_strategy_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrchestrateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestrateRequest) ProtoMessage() {}

func (x *OrchestrateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestrateRequest.ProtoReflect.Descriptor instead.
func (*OrchestrateRequest) Descriptor() ([]byte, []int) {
	return file_strategy_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *OrchestrateRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *OrchestrateRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type OrchestrateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Actions       []string               `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrchestrateResponse) Reset() {
	*x = OrchestrateResponse{}
	mi := &file_strategy_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrchestrateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestrateResponse) ProtoMessage() {}

func (x *OrchestrateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestrateResponse.ProtoReflect.Descriptor instead.
func (*OrchestrateResponse) Descriptor() ([]byte, []int) {
	return file_strategy_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *OrchestrateResponse) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *OrchestrateResponse) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

var File_strategy_orchestrator_proto protoreflect.FileDescriptor

const file_strategy_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x1bstrategy_orchestrator.proto\x12\bstrategy\"P\n" +
	"\x12OrchestrateRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\tR\auserIds\"P\n" +
	"\x13OrchestrateResponse\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12\x18\n" +
	"\aactions\x18\x02 \x03(\tR\aactions2b\n" +
	"\x14StrategyOrchestrator\x12J\n" +
	"\vOrchestrate\x12\x1c.strategy.OrchestrateRequest\x1a\x1d.strategy.OrchestrateResponseBLZJgithub.com/kiki-agent/services/syncshield/internal/strategy_orchestratorpbb\x06proto3"

var (
	file_strategy_orchestrator_proto_rawDescOnce sync.Once
	file_strategy_orchestrator_proto_rawDescData []byte
)

func file_strategy_orchestrator_proto_rawDescGZIP() []byte {
	file_strategy_orchestrator_proto_rawDescOnce.Do(func() {
		file_strategy_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_strategy_orchestrator_proto_rawDesc), len(file_strategy_orchestrator_proto_rawDesc)))
	})
	return file_strategy_orchestrator_proto_rawDescData
}

var file_strategy_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_strategy_orchestrator_proto_goTypes = []any{
	(*OrchestrateRequest)(nil),  // 0: strategy.OrchestrateRequest
	(*OrchestrateResponse)(nil), // 1: strategy.OrchestrateResponse
}
var file_strategy_orchestrator_proto_depIdxs = []int32{
	0, // 0: strategy.StrategyOrchestrator.Orchestrate:input_type -> strategy.OrchestrateRequest
	1, // 1: strategy.StrategyOrchestrator.Orchestrate:output_type -> strategy.OrchestrateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_strategy_orchestrator_proto_init() }
func file_strategy_orchestrator_proto_init() {
	if File_strategy_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_strategy_orchestrator_proto_rawDesc), len(file_strategy_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_strategy_orchestrator_proto_goTypes,
		DependencyIndexes: file_strategy_orchestrator_proto_depIdxs,
		MessageInfos:      file_strategy_orchestrator_proto_msgTypes,
	}.Build()
	File_strategy_orchestrator_proto = out.File
	file_strategy_orchestrator_proto_goTypes = nil
	file_strategy_orchestrator_proto_depIdxs = nil
}
