# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import kiki_core_pb2 as kiki__core__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kiki_core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StrategyOrchestratorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Coordinate = channel.unary_unary(
                '/kiki.StrategyOrchestrator/Coordinate',
                request_serializer=kiki__core__pb2.PlanRequest.SerializeToString,
                response_deserializer=kiki__core__pb2.PlanResponse.FromString,
                _registered_method=True)


class StrategyOrchestratorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Coordinate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StrategyOrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Coordinate': grpc.unary_unary_rpc_method_handler(
                    servicer.Coordinate,
                    request_deserializer=kiki__core__pb2.PlanRequest.FromString,
                    response_serializer=kiki__core__pb2.PlanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kiki.StrategyOrchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kiki.StrategyOrchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StrategyOrchestrator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Coordinate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiki.StrategyOrchestrator/Coordinate',
            kiki__core__pb2.PlanRequest.SerializeToString,
            kiki__core__pb2.PlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ValueEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictLTV = channel.unary_unary(
                '/kiki.ValueEngine/PredictLTV',
                request_serializer=kiki__core__pb2.DataRequest.SerializeToString,
                response_deserializer=kiki__core__pb2.LTVResult.FromString,
                _registered_method=True)


class ValueEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PredictLTV(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ValueEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictLTV': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictLTV,
                    request_deserializer=kiki__core__pb2.DataRequest.FromString,
                    response_serializer=kiki__core__pb2.LTVResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kiki.ValueEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kiki.ValueEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ValueEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictLTV(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiki.ValueEngine/PredictLTV',
            kiki__core__pb2.DataRequest.SerializeToString,
            kiki__core__pb2.LTVResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
