# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kiki_core.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fkiki_core.proto\x12\x04kiki\"\x8e\x01\n\x11ReasoningMetadata\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x13\n\x0b\x61\x63tion_type\x18\x02 \x01(\t\x12\x18\n\x10\x63onfidence_score\x18\x03 \x01(\x02\x12\x0e\n\x06intent\x18\x04 \x01(\t\x12\x10\n\x08\x65vidence\x18\x05 \x01(\t\x12\x16\n\x0ereasoning_text\x18\x06 \x01(\t\"/\n\x0bPlanRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\t\",\n\x0cPlanResponse\x12\x0c\n\x04plan\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"0\n\x0b\x44\x61taRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08\x66\x65\x61tures\x18\x02 \x03(\x02\"/\n\tLTVResult\x12\x0b\n\x03ltv\x18\x01 \x01(\x02\x12\x15\n\rmodel_version\x18\x02 \x01(\t\"]\n\x17GenerateCreativeRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05style\x18\x03 \x01(\t\x12\x12\n\nnum_images\x18\x04 \x01(\x05\">\n\x18GenerateCreativeResponse\x12\x12\n\nimage_urls\x18\x01 \x03(\t\x12\x0e\n\x06job_id\x18\x02 \x01(\t2K\n\x14StrategyOrchestrator\x12\x33\n\nCoordinate\x12\x11.kiki.PlanRequest\x1a\x12.kiki.PlanResponse2?\n\x0bValueEngine\x12\x30\n\nPredictLTV\x12\x11.kiki.DataRequest\x1a\x0f.kiki.LTVResult2f\n\x11\x43reativeGenerator\x12Q\n\x10GenerateCreative\x12\x1d.kiki.GenerateCreativeRequest\x1a\x1e.kiki.GenerateCreativeResponseB3Z1github.com/kiki_agent/shared/types/go/kiki_corepbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kiki_core_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z1github.com/kiki_agent/shared/types/go/kiki_corepb'
  _REASONINGMETADATA._serialized_start=26
  _REASONINGMETADATA._serialized_end=168
  _PLANREQUEST._serialized_start=170
  _PLANREQUEST._serialized_end=217
  _PLANRESPONSE._serialized_start=219
  _PLANRESPONSE._serialized_end=263
  _DATAREQUEST._serialized_start=265
  _DATAREQUEST._serialized_end=313
  _LTVRESULT._serialized_start=315
  _LTVRESULT._serialized_end=362
  _GENERATECREATIVEREQUEST._serialized_start=364
  _GENERATECREATIVEREQUEST._serialized_end=457
  _GENERATECREATIVERESPONSE._serialized_start=459
  _GENERATECREATIVERESPONSE._serialized_end=521
  _STRATEGYORCHESTRATOR._serialized_start=523
  _STRATEGYORCHESTRATOR._serialized_end=598
  _VALUEENGINE._serialized_start=600
  _VALUEENGINE._serialized_end=663
  _CREATIVEGENERATOR._serialized_start=665
  _CREATIVEGENERATOR._serialized_end=767
# @@protoc_insertion_point(module_scope)
