# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shield.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cshield.proto\x12\x06shield\"\x89\x01\n\x0c\x41uditRequest\x12\r\n\x05\x65vent\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12,\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x1e.shield.AuditRequest.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\".\n\rAuditResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05\x65vent\x18\x02 \x01(\t\"o\n\x0fRiskScanRequest\x12/\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32!.shield.RiskScanRequest.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\"\n\x10RiskScanResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x88\x01\n\x11\x43omplianceService\x12\x34\n\x05\x41udit\x12\x14.shield.AuditRequest\x1a\x15.shield.AuditResponse\x12=\n\x08RiskScan\x12\x17.shield.RiskScanRequest\x1a\x18.shield.RiskScanResponseB7Z5github.com/kiki-agent/shared/types/go/shield;shieldpbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shield_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z5github.com/kiki-agent/shared/types/go/shield;shieldpb'
  _AUDITREQUEST_DATAENTRY._options = None
  _AUDITREQUEST_DATAENTRY._serialized_options = b'8\001'
  _RISKSCANREQUEST_DATAENTRY._options = None
  _RISKSCANREQUEST_DATAENTRY._serialized_options = b'8\001'
  _AUDITREQUEST._serialized_start=25
  _AUDITREQUEST._serialized_end=162
  _AUDITREQUEST_DATAENTRY._serialized_start=119
  _AUDITREQUEST_DATAENTRY._serialized_end=162
  _AUDITRESPONSE._serialized_start=164
  _AUDITRESPONSE._serialized_end=210
  _RISKSCANREQUEST._serialized_start=212
  _RISKSCANREQUEST._serialized_end=323
  _RISKSCANREQUEST_DATAENTRY._serialized_start=119
  _RISKSCANREQUEST_DATAENTRY._serialized_end=162
  _RISKSCANRESPONSE._serialized_start=325
  _RISKSCANRESPONSE._serialized_end=359
  _COMPLIANCESERVICE._serialized_start=362
  _COMPLIANCESERVICE._serialized_end=498
# @@protoc_insertion_point(module_scope)
