// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: shield.proto

package shieldpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Data          map[string]string      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRequest) Reset() {
	*x = AuditRequest{}
	mi := &file_shield_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRequest) ProtoMessage() {}

func (x *AuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shield_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRequest.ProtoReflect.Descriptor instead.
func (*AuditRequest) Descriptor() ([]byte, []int) {
	return file_shield_proto_rawDescGZIP(), []int{0}
}

func (x *AuditRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *AuditRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuditRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type AuditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditResponse) Reset() {
	*x = AuditResponse{}
	mi := &file_shield_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditResponse) ProtoMessage() {}

func (x *AuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shield_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditResponse.ProtoReflect.Descriptor instead.
func (*AuditResponse) Descriptor() ([]byte, []int) {
	return file_shield_proto_rawDescGZIP(), []int{1}
}

func (x *AuditResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AuditResponse) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

type RiskScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string]string      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskScanRequest) Reset() {
	*x = RiskScanRequest{}
	mi := &file_shield_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskScanRequest) ProtoMessage() {}

func (x *RiskScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shield_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskScanRequest.ProtoReflect.Descriptor instead.
func (*RiskScanRequest) Descriptor() ([]byte, []int) {
	return file_shield_proto_rawDescGZIP(), []int{2}
}

func (x *RiskScanRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type RiskScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskScanResponse) Reset() {
	*x = RiskScanResponse{}
	mi := &file_shield_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskScanResponse) ProtoMessage() {}

func (x *RiskScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shield_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskScanResponse.ProtoReflect.Descriptor instead.
func (*RiskScanResponse) Descriptor() ([]byte, []int) {
	return file_shield_proto_rawDescGZIP(), []int{3}
}

func (x *RiskScanResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_shield_proto protoreflect.FileDescriptor

const file_shield_proto_rawDesc = "" +
	"\n" +
	"\fshield.proto\x12\x06shield\"\xaa\x01\n" +
	"\fAuditRequest\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x122\n" +
	"\x04data\x18\x03 \x03(\v2\x1e.shield.AuditRequest.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\rAuditResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\"\x81\x01\n" +
	"\x0fRiskScanRequest\x125\n" +
	"\x04data\x18\x01 \x03(\v2!.shield.RiskScanRequest.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"*\n" +
	"\x10RiskScanResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x88\x01\n" +
	"\x11ComplianceService\x124\n" +
	"\x05Audit\x12\x14.shield.AuditRequest\x1a\x15.shield.AuditResponse\x12=\n" +
	"\bRiskScan\x12\x17.shield.RiskScanRequest\x1a\x18.shield.RiskScanResponseB7Z5github.com/kiki-agent/shared/types/go/shield;shieldpbb\x06proto3"

var (
	file_shield_proto_rawDescOnce sync.Once
	file_shield_proto_rawDescData []byte
)

func file_shield_proto_rawDescGZIP() []byte {
	file_shield_proto_rawDescOnce.Do(func() {
		file_shield_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shield_proto_rawDesc), len(file_shield_proto_rawDesc)))
	})
	return file_shield_proto_rawDescData
}

var file_shield_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shield_proto_goTypes = []any{
	(*AuditRequest)(nil),     // 0: shield.AuditRequest
	(*AuditResponse)(nil),    // 1: shield.AuditResponse
	(*RiskScanRequest)(nil),  // 2: shield.RiskScanRequest
	(*RiskScanResponse)(nil), // 3: shield.RiskScanResponse
	nil,                      // 4: shield.AuditRequest.DataEntry
	nil,                      // 5: shield.RiskScanRequest.DataEntry
}
var file_shield_proto_depIdxs = []int32{
	4, // 0: shield.AuditRequest.data:type_name -> shield.AuditRequest.DataEntry
	5, // 1: shield.RiskScanRequest.data:type_name -> shield.RiskScanRequest.DataEntry
	0, // 2: shield.ComplianceService.Audit:input_type -> shield.AuditRequest
	2, // 3: shield.ComplianceService.RiskScan:input_type -> shield.RiskScanRequest
	1, // 4: shield.ComplianceService.Audit:output_type -> shield.AuditResponse
	3, // 5: shield.ComplianceService.RiskScan:output_type -> shield.RiskScanResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shield_proto_init() }
func file_shield_proto_init() {
	if File_shield_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shield_proto_rawDesc), len(file_shield_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shield_proto_goTypes,
		DependencyIndexes: file_shield_proto_depIdxs,
		MessageInfos:      file_shield_proto_msgTypes,
	}.Build()
	File_shield_proto = out.File
	file_shield_proto_goTypes = nil
	file_shield_proto_depIdxs = nil
}
