// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: safefail.proto

package sfpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SafeFailService_TriggerRollback_FullMethodName = "/safefail.SafeFailService/TriggerRollback"
	SafeFailService_GetStatus_FullMethodName       = "/safefail.SafeFailService/GetStatus"
)

// SafeFailServiceClient is the client API for SafeFailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SafeFailServiceClient interface {
	TriggerRollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error)
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type safeFailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSafeFailServiceClient(cc grpc.ClientConnInterface) SafeFailServiceClient {
	return &safeFailServiceClient{cc}
}

func (c *safeFailServiceClient) TriggerRollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackResponse)
	err := c.cc.Invoke(ctx, SafeFailService_TriggerRollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *safeFailServiceClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, SafeFailService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SafeFailServiceServer is the server API for SafeFailService service.
// All implementations must embed UnimplementedSafeFailServiceServer
// for forward compatibility.
type SafeFailServiceServer interface {
	TriggerRollback(context.Context, *RollbackRequest) (*RollbackResponse, error)
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedSafeFailServiceServer()
}

// UnimplementedSafeFailServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSafeFailServiceServer struct{}

func (UnimplementedSafeFailServiceServer) TriggerRollback(context.Context, *RollbackRequest) (*RollbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerRollback not implemented")
}
func (UnimplementedSafeFailServiceServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedSafeFailServiceServer) mustEmbedUnimplementedSafeFailServiceServer() {}
func (UnimplementedSafeFailServiceServer) testEmbeddedByValue()                         {}

// UnsafeSafeFailServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SafeFailServiceServer will
// result in compilation errors.
type UnsafeSafeFailServiceServer interface {
	mustEmbedUnimplementedSafeFailServiceServer()
}

func RegisterSafeFailServiceServer(s grpc.ServiceRegistrar, srv SafeFailServiceServer) {
	// If the following call panics, it indicates UnimplementedSafeFailServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SafeFailService_ServiceDesc, srv)
}

func _SafeFailService_TriggerRollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SafeFailServiceServer).TriggerRollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SafeFailService_TriggerRollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SafeFailServiceServer).TriggerRollback(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SafeFailService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SafeFailServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SafeFailService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SafeFailServiceServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SafeFailService_ServiceDesc is the grpc.ServiceDesc for SafeFailService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SafeFailService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "safefail.SafeFailService",
	HandlerType: (*SafeFailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TriggerRollback",
			Handler:    _SafeFailService_TriggerRollback_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _SafeFailService_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "safefail.proto",
}
