// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: safefail.proto

package sfpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RollbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_safefail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_safefail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_safefail_proto_rawDescGZIP(), []int{0}
}

func (x *RollbackRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RollbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackResponse) Reset() {
	*x = RollbackResponse{}
	mi := &file_safefail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackResponse) ProtoMessage() {}

func (x *RollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_safefail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackResponse.ProtoReflect.Descriptor instead.
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return file_safefail_proto_rawDescGZIP(), []int{1}
}

func (x *RollbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RollbackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_safefail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_safefail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_safefail_proto_rawDescGZIP(), []int{2}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastScore     float64                `protobuf:"fixed64,1,opt,name=lastScore,proto3" json:"lastScore,omitempty"`
	ThresholdDrop float64                `protobuf:"fixed64,2,opt,name=thresholdDrop,proto3" json:"thresholdDrop,omitempty"`
	ThresholdNeg  int32                  `protobuf:"varint,3,opt,name=thresholdNeg,proto3" json:"thresholdNeg,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_safefail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_safefail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_safefail_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetLastScore() float64 {
	if x != nil {
		return x.LastScore
	}
	return 0
}

func (x *StatusResponse) GetThresholdDrop() float64 {
	if x != nil {
		return x.ThresholdDrop
	}
	return 0
}

func (x *StatusResponse) GetThresholdNeg() int32 {
	if x != nil {
		return x.ThresholdNeg
	}
	return 0
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_safefail_proto protoreflect.FileDescriptor

const file_safefail_proto_rawDesc = "" +
	"\n" +
	"\x0esafefail.proto\x12\bsafefail\")\n" +
	"\x0fRollbackRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"F\n" +
	"\x10RollbackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0f\n" +
	"\rStatusRequest\"\x90\x01\n" +
	"\x0eStatusResponse\x12\x1c\n" +
	"\tlastScore\x18\x01 \x01(\x01R\tlastScore\x12$\n" +
	"\rthresholdDrop\x18\x02 \x01(\x01R\rthresholdDrop\x12\"\n" +
	"\fthresholdNeg\x18\x03 \x01(\x05R\fthresholdNeg\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status2\x9b\x01\n" +
	"\x0fSafeFailService\x12H\n" +
	"\x0fTriggerRollback\x12\x19.safefail.RollbackRequest\x1a\x1a.safefail.RollbackResponse\x12>\n" +
	"\tGetStatus\x12\x17.safefail.StatusRequest\x1a\x18.safefail.StatusResponseB9Z7github.com/kiki-agent/services/syncshield/safefail;sfpbb\x06proto3"

var (
	file_safefail_proto_rawDescOnce sync.Once
	file_safefail_proto_rawDescData []byte
)

func file_safefail_proto_rawDescGZIP() []byte {
	file_safefail_proto_rawDescOnce.Do(func() {
		file_safefail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_safefail_proto_rawDesc), len(file_safefail_proto_rawDesc)))
	})
	return file_safefail_proto_rawDescData
}

var file_safefail_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_safefail_proto_goTypes = []any{
	(*RollbackRequest)(nil),  // 0: safefail.RollbackRequest
	(*RollbackResponse)(nil), // 1: safefail.RollbackResponse
	(*StatusRequest)(nil),    // 2: safefail.StatusRequest
	(*StatusResponse)(nil),   // 3: safefail.StatusResponse
}
var file_safefail_proto_depIdxs = []int32{
	0, // 0: safefail.SafeFailService.TriggerRollback:input_type -> safefail.RollbackRequest
	2, // 1: safefail.SafeFailService.GetStatus:input_type -> safefail.StatusRequest
	1, // 2: safefail.SafeFailService.TriggerRollback:output_type -> safefail.RollbackResponse
	3, // 3: safefail.SafeFailService.GetStatus:output_type -> safefail.StatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_safefail_proto_init() }
func file_safefail_proto_init() {
	if File_safefail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_safefail_proto_rawDesc), len(file_safefail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_safefail_proto_goTypes,
		DependencyIndexes: file_safefail_proto_depIdxs,
		MessageInfos:      file_safefail_proto_msgTypes,
	}.Build()
	File_safefail_proto = out.File
	file_safefail_proto_goTypes = nil
	file_safefail_proto_depIdxs = nil
}
