// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: brain.proto

package brainpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrchestrateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	UserIds       []string               `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Context       map[string]string      `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrchestrateRequest) Reset() {
	*x = OrchestrateRequest{}
	mi := &file_brain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrchestrateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestrateRequest) ProtoMessage() {}

func (x *OrchestrateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestrateRequest.ProtoReflect.Descriptor instead.
func (*OrchestrateRequest) Descriptor() ([]byte, []int) {
	return file_brain_proto_rawDescGZIP(), []int{0}
}

func (x *OrchestrateRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *OrchestrateRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *OrchestrateRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type OrchestrateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Actions       []string               `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrchestrateResponse) Reset() {
	*x = OrchestrateResponse{}
	mi := &file_brain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrchestrateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestrateResponse) ProtoMessage() {}

func (x *OrchestrateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestrateResponse.ProtoReflect.Descriptor instead.
func (*OrchestrateResponse) Descriptor() ([]byte, []int) {
	return file_brain_proto_rawDescGZIP(), []int{1}
}

func (x *OrchestrateResponse) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *OrchestrateResponse) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *OrchestrateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_brain_proto protoreflect.FileDescriptor

const file_brain_proto_rawDesc = "" +
	"\n" +
	"\vbrain.proto\x12\x05brain\"\xce\x01\n" +
	"\x12OrchestrateRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\tR\auserIds\x12@\n" +
	"\acontext\x18\x03 \x03(\v2&.brain.OrchestrateRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"h\n" +
	"\x13OrchestrateResponse\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12\x18\n" +
	"\aactions\x18\x02 \x03(\tR\aactions\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2\\\n" +
	"\x14StrategyOrchestrator\x12D\n" +
	"\vOrchestrate\x12\x19.brain.OrchestrateRequest\x1a\x1a.brain.OrchestrateResponseB5Z3github.com/kiki-agent/shared/types/go/brain;brainpbb\x06proto3"

var (
	file_brain_proto_rawDescOnce sync.Once
	file_brain_proto_rawDescData []byte
)

func file_brain_proto_rawDescGZIP() []byte {
	file_brain_proto_rawDescOnce.Do(func() {
		file_brain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_brain_proto_rawDesc), len(file_brain_proto_rawDesc)))
	})
	return file_brain_proto_rawDescData
}

var file_brain_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_brain_proto_goTypes = []any{
	(*OrchestrateRequest)(nil),  // 0: brain.OrchestrateRequest
	(*OrchestrateResponse)(nil), // 1: brain.OrchestrateResponse
	nil,                         // 2: brain.OrchestrateRequest.ContextEntry
}
var file_brain_proto_depIdxs = []int32{
	2, // 0: brain.OrchestrateRequest.context:type_name -> brain.OrchestrateRequest.ContextEntry
	0, // 1: brain.StrategyOrchestrator.Orchestrate:input_type -> brain.OrchestrateRequest
	1, // 2: brain.StrategyOrchestrator.Orchestrate:output_type -> brain.OrchestrateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_brain_proto_init() }
func file_brain_proto_init() {
	if File_brain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_brain_proto_rawDesc), len(file_brain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_brain_proto_goTypes,
		DependencyIndexes: file_brain_proto_depIdxs,
		MessageInfos:      file_brain_proto_msgTypes,
	}.Build()
	File_brain_proto = out.File
	file_brain_proto_goTypes = nil
	file_brain_proto_depIdxs = nil
}
