# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cms_integration_pb2 as cms__integration__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cms_integration_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SyncValueServiceStub(object):
    """========================================================================
    SyncValue™ Service - LTV Predictions & Baseline Updates
    ========================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateCustomerLTV = channel.unary_unary(
                '/kiki.cms.SyncValueService/UpdateCustomerLTV',
                request_serializer=cms__integration__pb2.CustomerLTVUpdateRequest.SerializeToString,
                response_deserializer=cms__integration__pb2.CustomerLTVUpdateResponse.FromString,
                _registered_method=True)
        self.UpdateBaselineMetrics = channel.unary_unary(
                '/kiki.cms.SyncValueService/UpdateBaselineMetrics',
                request_serializer=cms__integration__pb2.BaselineUpdateRequest.SerializeToString,
                response_deserializer=cms__integration__pb2.BaselineUpdateResponse.FromString,
                _registered_method=True)
        self.GetCustomerLTV = channel.unary_unary(
                '/kiki.cms.SyncValueService/GetCustomerLTV',
                request_serializer=cms__integration__pb2.CustomerLTVRequest.SerializeToString,
                response_deserializer=cms__integration__pb2.CustomerLTVResponse.FromString,
                _registered_method=True)
        self.BatchUpdateOrders = channel.unary_unary(
                '/kiki.cms.SyncValueService/BatchUpdateOrders',
                request_serializer=cms__integration__pb2.BatchOrdersRequest.SerializeToString,
                response_deserializer=cms__integration__pb2.BatchOrdersResponse.FromString,
                _registered_method=True)


class SyncValueServiceServicer(object):
    """========================================================================
    SyncValue™ Service - LTV Predictions & Baseline Updates
    ========================================================================

    """

    def UpdateCustomerLTV(self, request, context):
        """Update customer LTV prediction based on new order
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBaselineMetrics(self, request, context):
        """Recalculate baseline metrics for OaaS comparison
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCustomerLTV(self, request, context):
        """Get LTV prediction for attribution scoring
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchUpdateOrders(self, request, context):
        """Batch update for historical data sync
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SyncValueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateCustomerLTV': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCustomerLTV,
                    request_deserializer=cms__integration__pb2.CustomerLTVUpdateRequest.FromString,
                    response_serializer=cms__integration__pb2.CustomerLTVUpdateResponse.SerializeToString,
            ),
            'UpdateBaselineMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBaselineMetrics,
                    request_deserializer=cms__integration__pb2.BaselineUpdateRequest.FromString,
                    response_serializer=cms__integration__pb2.BaselineUpdateResponse.SerializeToString,
            ),
            'GetCustomerLTV': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCustomerLTV,
                    request_deserializer=cms__integration__pb2.CustomerLTVRequest.FromString,
                    response_serializer=cms__integration__pb2.CustomerLTVResponse.SerializeToString,
            ),
            'BatchUpdateOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchUpdateOrders,
                    request_deserializer=cms__integration__pb2.BatchOrdersRequest.FromString,
                    response_serializer=cms__integration__pb2.BatchOrdersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kiki.cms.SyncValueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kiki.cms.SyncValueService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SyncValueService(object):
    """========================================================================
    SyncValue™ Service - LTV Predictions & Baseline Updates
    ========================================================================

    """

    @staticmethod
    def UpdateCustomerLTV(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiki.cms.SyncValueService/UpdateCustomerLTV',
            cms__integration__pb2.CustomerLTVUpdateRequest.SerializeToString,
            cms__integration__pb2.CustomerLTVUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBaselineMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiki.cms.SyncValueService/UpdateBaselineMetrics',
            cms__integration__pb2.BaselineUpdateRequest.SerializeToString,
            cms__integration__pb2.BaselineUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCustomerLTV(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiki.cms.SyncValueService/GetCustomerLTV',
            cms__integration__pb2.CustomerLTVRequest.SerializeToString,
            cms__integration__pb2.CustomerLTVResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchUpdateOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiki.cms.SyncValueService/BatchUpdateOrders',
            cms__integration__pb2.BatchOrdersRequest.SerializeToString,
            cms__integration__pb2.BatchOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SyncFlowServiceStub(object):
    """========================================================================
    SyncFlow™ Service - Circuit Breaker & Bid Adjustments
    ========================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PauseProductCampaigns = channel.unary_unary(
                '/kiki.cms.SyncFlowService/PauseProductCampaigns',
                request_serializer=cms__integration__pb2.PauseCampaignsRequest.SerializeToString,
                response_deserializer=cms__integration__pb2.PauseCampaignsResponse.FromString,
                _registered_method=True)
        self.ResumeProductCampaigns = channel.unary_unary(
                '/kiki.cms.SyncFlowService/ResumeProductCampaigns',
                request_serializer=cms__integration__pb2.ResumeCampaignsRequest.SerializeToString,
                response_deserializer=cms__integration__pb2.ResumeCampaignsResponse.FromString,
                _registered_method=True)
        self.AdjustBidsForInventory = channel.unary_unary(
                '/kiki.cms.SyncFlowService/AdjustBidsForInventory',
                request_serializer=cms__integration__pb2.BidAdjustmentRequest.SerializeToString,
                response_deserializer=cms__integration__pb2.BidAdjustmentResponse.FromString,
                _registered_method=True)
        self.UpdateProductMargins = channel.unary_unary(
                '/kiki.cms.SyncFlowService/UpdateProductMargins',
                request_serializer=cms__integration__pb2.ProductMarginsRequest.SerializeToString,
                response_deserializer=cms__integration__pb2.ProductMarginsResponse.FromString,
                _registered_method=True)


class SyncFlowServiceServicer(object):
    """========================================================================
    SyncFlow™ Service - Circuit Breaker & Bid Adjustments
    ========================================================================

    """

    def PauseProductCampaigns(self, request, context):
        """Pause campaigns for out-of-stock product (circuit breaker)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeProductCampaigns(self, request, context):
        """Resume campaigns when product is restocked
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdjustBidsForInventory(self, request, context):
        """Adjust bids based on inventory levels
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProductMargins(self, request, context):
        """Update product margins for profitability-based bidding
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SyncFlowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PauseProductCampaigns': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseProductCampaigns,
                    request_deserializer=cms__integration__pb2.PauseCampaignsRequest.FromString,
                    response_serializer=cms__integration__pb2.PauseCampaignsResponse.SerializeToString,
            ),
            'ResumeProductCampaigns': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeProductCampaigns,
                    request_deserializer=cms__integration__pb2.ResumeCampaignsRequest.FromString,
                    response_serializer=cms__integration__pb2.ResumeCampaignsResponse.SerializeToString,
            ),
            'AdjustBidsForInventory': grpc.unary_unary_rpc_method_handler(
                    servicer.AdjustBidsForInventory,
                    request_deserializer=cms__integration__pb2.BidAdjustmentRequest.FromString,
                    response_serializer=cms__integration__pb2.BidAdjustmentResponse.SerializeToString,
            ),
            'UpdateProductMargins': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProductMargins,
                    request_deserializer=cms__integration__pb2.ProductMarginsRequest.FromString,
                    response_serializer=cms__integration__pb2.ProductMarginsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kiki.cms.SyncFlowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kiki.cms.SyncFlowService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SyncFlowService(object):
    """========================================================================
    SyncFlow™ Service - Circuit Breaker & Bid Adjustments
    ========================================================================

    """

    @staticmethod
    def PauseProductCampaigns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiki.cms.SyncFlowService/PauseProductCampaigns',
            cms__integration__pb2.PauseCampaignsRequest.SerializeToString,
            cms__integration__pb2.PauseCampaignsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeProductCampaigns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiki.cms.SyncFlowService/ResumeProductCampaigns',
            cms__integration__pb2.ResumeCampaignsRequest.SerializeToString,
            cms__integration__pb2.ResumeCampaignsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdjustBidsForInventory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiki.cms.SyncFlowService/AdjustBidsForInventory',
            cms__integration__pb2.BidAdjustmentRequest.SerializeToString,
            cms__integration__pb2.BidAdjustmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProductMargins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiki.cms.SyncFlowService/UpdateProductMargins',
            cms__integration__pb2.ProductMarginsRequest.SerializeToString,
            cms__integration__pb2.ProductMarginsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SyncLedgerServiceStub(object):
    """========================================================================
    SyncLedger™ Service - OaaS Settlement & Revenue Tracking
    ========================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecordIncrementalRevenue = channel.unary_unary(
                '/kiki.cms.SyncLedgerService/RecordIncrementalRevenue',
                request_serializer=cms__integration__pb2.IncrementalRevenueRequest.SerializeToString,
                response_deserializer=cms__integration__pb2.IncrementalRevenueResponse.FromString,
                _registered_method=True)
        self.CalculateSuccessFee = channel.unary_unary(
                '/kiki.cms.SyncLedgerService/CalculateSuccessFee',
                request_serializer=cms__integration__pb2.SuccessFeeRequest.SerializeToString,
                response_deserializer=cms__integration__pb2.SuccessFeeResponse.FromString,
                _registered_method=True)
        self.GetOrderAttribution = channel.unary_unary(
                '/kiki.cms.SyncLedgerService/GetOrderAttribution',
                request_serializer=cms__integration__pb2.OrderAttributionRequest.SerializeToString,
                response_deserializer=cms__integration__pb2.OrderAttributionResponse.FromString,
                _registered_method=True)


class SyncLedgerServiceServicer(object):
    """========================================================================
    SyncLedger™ Service - OaaS Settlement & Revenue Tracking
    ========================================================================

    """

    def RecordIncrementalRevenue(self, request, context):
        """Record incremental revenue for OaaS billing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateSuccessFee(self, request, context):
        """Calculate OaaS success fee for billing period
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderAttribution(self, request, context):
        """Get attribution data for specific order
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SyncLedgerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecordIncrementalRevenue': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordIncrementalRevenue,
                    request_deserializer=cms__integration__pb2.IncrementalRevenueRequest.FromString,
                    response_serializer=cms__integration__pb2.IncrementalRevenueResponse.SerializeToString,
            ),
            'CalculateSuccessFee': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateSuccessFee,
                    request_deserializer=cms__integration__pb2.SuccessFeeRequest.FromString,
                    response_serializer=cms__integration__pb2.SuccessFeeResponse.SerializeToString,
            ),
            'GetOrderAttribution': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderAttribution,
                    request_deserializer=cms__integration__pb2.OrderAttributionRequest.FromString,
                    response_serializer=cms__integration__pb2.OrderAttributionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kiki.cms.SyncLedgerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kiki.cms.SyncLedgerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SyncLedgerService(object):
    """========================================================================
    SyncLedger™ Service - OaaS Settlement & Revenue Tracking
    ========================================================================

    """

    @staticmethod
    def RecordIncrementalRevenue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiki.cms.SyncLedgerService/RecordIncrementalRevenue',
            cms__integration__pb2.IncrementalRevenueRequest.SerializeToString,
            cms__integration__pb2.IncrementalRevenueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateSuccessFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiki.cms.SyncLedgerService/CalculateSuccessFee',
            cms__integration__pb2.SuccessFeeRequest.SerializeToString,
            cms__integration__pb2.SuccessFeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderAttribution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiki.cms.SyncLedgerService/GetOrderAttribution',
            cms__integration__pb2.OrderAttributionRequest.SerializeToString,
            cms__integration__pb2.OrderAttributionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SyncCreateServiceStub(object):
    """========================================================================
    SyncCreate™ Service - Creative Generation from Product Feeds
    ========================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateProductCreative = channel.unary_unary(
                '/kiki.cms.SyncCreateService/GenerateProductCreative',
                request_serializer=cms__integration__pb2.ProductCreativeRequest.SerializeToString,
                response_deserializer=cms__integration__pb2.ProductCreativeResponse.FromString,
                _registered_method=True)
        self.BatchGenerateCreatives = channel.unary_unary(
                '/kiki.cms.SyncCreateService/BatchGenerateCreatives',
                request_serializer=cms__integration__pb2.BatchCreativeRequest.SerializeToString,
                response_deserializer=cms__integration__pb2.BatchCreativeResponse.FromString,
                _registered_method=True)
        self.RefreshProductCreative = channel.unary_unary(
                '/kiki.cms.SyncCreateService/RefreshProductCreative',
                request_serializer=cms__integration__pb2.RefreshCreativeRequest.SerializeToString,
                response_deserializer=cms__integration__pb2.RefreshCreativeResponse.FromString,
                _registered_method=True)


class SyncCreateServiceServicer(object):
    """========================================================================
    SyncCreate™ Service - Creative Generation from Product Feeds
    ========================================================================

    """

    def GenerateProductCreative(self, request, context):
        """Generate ad creative from product data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGenerateCreatives(self, request, context):
        """Batch generate creatives for new product sync
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshProductCreative(self, request, context):
        """Notify of product update for creative refresh
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SyncCreateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateProductCreative': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateProductCreative,
                    request_deserializer=cms__integration__pb2.ProductCreativeRequest.FromString,
                    response_serializer=cms__integration__pb2.ProductCreativeResponse.SerializeToString,
            ),
            'BatchGenerateCreatives': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGenerateCreatives,
                    request_deserializer=cms__integration__pb2.BatchCreativeRequest.FromString,
                    response_serializer=cms__integration__pb2.BatchCreativeResponse.SerializeToString,
            ),
            'RefreshProductCreative': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshProductCreative,
                    request_deserializer=cms__integration__pb2.RefreshCreativeRequest.FromString,
                    response_serializer=cms__integration__pb2.RefreshCreativeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kiki.cms.SyncCreateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kiki.cms.SyncCreateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SyncCreateService(object):
    """========================================================================
    SyncCreate™ Service - Creative Generation from Product Feeds
    ========================================================================

    """

    @staticmethod
    def GenerateProductCreative(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiki.cms.SyncCreateService/GenerateProductCreative',
            cms__integration__pb2.ProductCreativeRequest.SerializeToString,
            cms__integration__pb2.ProductCreativeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchGenerateCreatives(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiki.cms.SyncCreateService/BatchGenerateCreatives',
            cms__integration__pb2.BatchCreativeRequest.SerializeToString,
            cms__integration__pb2.BatchCreativeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshProductCreative(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiki.cms.SyncCreateService/RefreshProductCreative',
            cms__integration__pb2.RefreshCreativeRequest.SerializeToString,
            cms__integration__pb2.RefreshCreativeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SyncEngageServiceStub(object):
    """========================================================================
    SyncEngage™ Service - Customer Lifecycle Triggers
    ========================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TriggerPostPurchaseFlow = channel.unary_unary(
                '/kiki.cms.SyncEngageService/TriggerPostPurchaseFlow',
                request_serializer=cms__integration__pb2.PostPurchaseRequest.SerializeToString,
                response_deserializer=cms__integration__pb2.PostPurchaseResponse.FromString,
                _registered_method=True)
        self.TriggerChurnPrevention = channel.unary_unary(
                '/kiki.cms.SyncEngageService/TriggerChurnPrevention',
                request_serializer=cms__integration__pb2.ChurnPreventionRequest.SerializeToString,
                response_deserializer=cms__integration__pb2.ChurnPreventionResponse.FromString,
                _registered_method=True)
        self.TriggerUpsellFlow = channel.unary_unary(
                '/kiki.cms.SyncEngageService/TriggerUpsellFlow',
                request_serializer=cms__integration__pb2.UpsellRequest.SerializeToString,
                response_deserializer=cms__integration__pb2.UpsellResponse.FromString,
                _registered_method=True)


class SyncEngageServiceServicer(object):
    """========================================================================
    SyncEngage™ Service - Customer Lifecycle Triggers
    ========================================================================

    """

    def TriggerPostPurchaseFlow(self, request, context):
        """Trigger post-purchase nurture flow
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerChurnPrevention(self, request, context):
        """Trigger churn prevention for at-risk customers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerUpsellFlow(self, request, context):
        """Trigger upsell/cross-sell based on purchase history
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SyncEngageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TriggerPostPurchaseFlow': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerPostPurchaseFlow,
                    request_deserializer=cms__integration__pb2.PostPurchaseRequest.FromString,
                    response_serializer=cms__integration__pb2.PostPurchaseResponse.SerializeToString,
            ),
            'TriggerChurnPrevention': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerChurnPrevention,
                    request_deserializer=cms__integration__pb2.ChurnPreventionRequest.FromString,
                    response_serializer=cms__integration__pb2.ChurnPreventionResponse.SerializeToString,
            ),
            'TriggerUpsellFlow': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerUpsellFlow,
                    request_deserializer=cms__integration__pb2.UpsellRequest.FromString,
                    response_serializer=cms__integration__pb2.UpsellResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kiki.cms.SyncEngageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kiki.cms.SyncEngageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SyncEngageService(object):
    """========================================================================
    SyncEngage™ Service - Customer Lifecycle Triggers
    ========================================================================

    """

    @staticmethod
    def TriggerPostPurchaseFlow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiki.cms.SyncEngageService/TriggerPostPurchaseFlow',
            cms__integration__pb2.PostPurchaseRequest.SerializeToString,
            cms__integration__pb2.PostPurchaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerChurnPrevention(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiki.cms.SyncEngageService/TriggerChurnPrevention',
            cms__integration__pb2.ChurnPreventionRequest.SerializeToString,
            cms__integration__pb2.ChurnPreventionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerUpsellFlow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiki.cms.SyncEngageService/TriggerUpsellFlow',
            cms__integration__pb2.UpsellRequest.SerializeToString,
            cms__integration__pb2.UpsellResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SyncShieldServiceStub(object):
    """========================================================================
    SyncShield™ Service - Audit Logging & Encryption
    ========================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LogDataAccess = channel.unary_unary(
                '/kiki.cms.SyncShieldService/LogDataAccess',
                request_serializer=cms__integration__pb2.DataAccessLogRequest.SerializeToString,
                response_deserializer=cms__integration__pb2.DataAccessLogResponse.FromString,
                _registered_method=True)
        self.EncryptCustomerData = channel.unary_unary(
                '/kiki.cms.SyncShieldService/EncryptCustomerData',
                request_serializer=cms__integration__pb2.EncryptRequest.SerializeToString,
                response_deserializer=cms__integration__pb2.EncryptResponse.FromString,
                _registered_method=True)
        self.DecryptCustomerData = channel.unary_unary(
                '/kiki.cms.SyncShieldService/DecryptCustomerData',
                request_serializer=cms__integration__pb2.DecryptRequest.SerializeToString,
                response_deserializer=cms__integration__pb2.DecryptResponse.FromString,
                _registered_method=True)
        self.LogWebhookEvent = channel.unary_unary(
                '/kiki.cms.SyncShieldService/LogWebhookEvent',
                request_serializer=cms__integration__pb2.WebhookLogRequest.SerializeToString,
                response_deserializer=cms__integration__pb2.WebhookLogResponse.FromString,
                _registered_method=True)


class SyncShieldServiceServicer(object):
    """========================================================================
    SyncShield™ Service - Audit Logging & Encryption
    ========================================================================

    """

    def LogDataAccess(self, request, context):
        """Log CMS data access for GDPR/CCPA compliance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EncryptCustomerData(self, request, context):
        """Encrypt sensitive customer data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecryptCustomerData(self, request, context):
        """Decrypt customer data for processing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogWebhookEvent(self, request, context):
        """Log webhook processing event
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SyncShieldServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LogDataAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.LogDataAccess,
                    request_deserializer=cms__integration__pb2.DataAccessLogRequest.FromString,
                    response_serializer=cms__integration__pb2.DataAccessLogResponse.SerializeToString,
            ),
            'EncryptCustomerData': grpc.unary_unary_rpc_method_handler(
                    servicer.EncryptCustomerData,
                    request_deserializer=cms__integration__pb2.EncryptRequest.FromString,
                    response_serializer=cms__integration__pb2.EncryptResponse.SerializeToString,
            ),
            'DecryptCustomerData': grpc.unary_unary_rpc_method_handler(
                    servicer.DecryptCustomerData,
                    request_deserializer=cms__integration__pb2.DecryptRequest.FromString,
                    response_serializer=cms__integration__pb2.DecryptResponse.SerializeToString,
            ),
            'LogWebhookEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.LogWebhookEvent,
                    request_deserializer=cms__integration__pb2.WebhookLogRequest.FromString,
                    response_serializer=cms__integration__pb2.WebhookLogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kiki.cms.SyncShieldService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kiki.cms.SyncShieldService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SyncShieldService(object):
    """========================================================================
    SyncShield™ Service - Audit Logging & Encryption
    ========================================================================

    """

    @staticmethod
    def LogDataAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiki.cms.SyncShieldService/LogDataAccess',
            cms__integration__pb2.DataAccessLogRequest.SerializeToString,
            cms__integration__pb2.DataAccessLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EncryptCustomerData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiki.cms.SyncShieldService/EncryptCustomerData',
            cms__integration__pb2.EncryptRequest.SerializeToString,
            cms__integration__pb2.EncryptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecryptCustomerData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiki.cms.SyncShieldService/DecryptCustomerData',
            cms__integration__pb2.DecryptRequest.SerializeToString,
            cms__integration__pb2.DecryptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LogWebhookEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiki.cms.SyncShieldService/LogWebhookEvent',
            cms__integration__pb2.WebhookLogRequest.SerializeToString,
            cms__integration__pb2.WebhookLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
