apiVersion: apps/v1
kind: Deployment
metadata:
  name: acquisition-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: acquisition-agent
  template:
    metadata:
      labels:
        app: acquisition-agent
    spec:
      containers:
      - name: acquisition-agent
        image: acquisition-agent:latest
        env:
        - name: ADAPTER
          value: "MockAdapter"
        - name: AUDIT_LOG_PATH
          value: "/var/log/acquisition_audit.log"
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: acquisition-agent
spec:
  selector:
    app: acquisition-agent
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
